### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'formatAddress')

### ISSUE THREAD

**Issue by chevymusclecar** [DimensionDev/Maskbook#10243]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'formatAddress')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'formatAddress')
  at useAccount (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/3689.js:20691:19)
  at ChainContextProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/3689.js:20909:94)
  at Jf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:425:143)
  at rh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:469:172)
  at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:588:88)
  at Bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:572:321)
  at Ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:423)
  at ef (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:264)
  at ff (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:565:94)
  at cf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:419:283)
  at bf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:420:408)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:422:276</pre>

## Build info
- Version: 2.21.4
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: 2023-07-28T13:35:17.767Z

## Git (*):

2a027e445b5f421907abb820c4e141f2e1b7c393 (HEAD)

**Comment by AinuX** [comment]
Hi,

Thank you for using our product and providing feedback to us. We also sincerely apologize for any inconvenience caused during your use.

This issue has been fixed in version 2.21.5. Please try upgrading the extension version. If the problem still persists, please reopen this issue.
