### ISSUE TITLE
[Crash] TypeError: Cannot destructure property 'share' of '(0 , entry_dom.tE)(...)' as it is undefined.

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#10826]
I was *doing something...*, then Mask reports an error.

> Cannot destructure property 'share' of '(0 , entry_dom.tE)(...)' as it is undefined.

Error stack:

<pre>TypeError: Cannot destructure property 'share' of '(0 , entry_dom.tE)(...)' as it is undefined.
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/chunk.9748.js:3727:13
  at Hf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:417:143)
  at ih (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:455:57)
  at Ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:584:97)
  at yk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:564:321)
  at xk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:562:30)
  at cf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:561:312)
  at df (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:556:94)
  at af (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:411:283)
  at $e (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:412:408)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:414:276</pre>

## Build info
- Version: 2.22.5
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: 2023-09-14T04:36:32.063Z

## Git (*):
86a85b35d7c42ad9017128b944829b90e5272a16 (HEAD)

**Comment by Tedko** [comment]
is this fixed @guanbinrui
