### ISSUE TITLE
[Crash] Error: Unknown chainId: 137. It might too early to access network state.

### ISSUE THREAD

**Issue by may176** [DimensionDev/Maskbook#10904]
I was *doing something...*, then Mask reports an error.

> Unknown chainId: 137. It might too early to access network state.

Error stack:

<pre>Error: Unknown chainId: 137. It might too early to access network state.
    at SolanaChainResolverAPI.getDescriptorRequired (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/3860.js:21627:32)
    at ChainResolverAPI_Base.nativeCurrency (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/3860.js:21617:47)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/691.js:2374:68
    at Object.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:438:413)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/3860.js:70015:125)
    at FungibleTokenList (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/691.js:2374:42)
    at Hf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:417:143)
    at Ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:578:338)
    at yk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:564:321)
    at xk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:562:30)
    at cf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:561:312)
    at df (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:556:94)
    at af (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:411:283)
    at $e (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:412:408)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:414:276</pre>

## Build info
- Version: 2.23.0
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: 2023-10-04T16:02:37.336Z

## Git (*):
e2cd82632d60d1f48071bcbb2ae1056f4ca3930d (release/2.23.0)

**Comment by may176** [comment]
已修复

**Comment by UncleBill** [comment]
fixed by https://github.com/DimensionDev/Maskbook/pull/10902
