### ISSUE TITLE
[Crash] InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#10954]
I was *doing something...*, then Mask reports an error.

> Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

Error stack:

<pre>Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
  at useUserContext (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/popups.js:107:52)
  at Provider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/8201.js:4087:17)
  at Hf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:117:143)
  at Ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:278:338)
  at yk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:264:321)
  at xk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:262:30)
  at cf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:261:312)
  at df (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:256:94)
  at af (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:111:283)
  at $e (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:112:408)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:114:276</pre>

## Build info
- Version: 2.23.1
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: 2023-10-12T04:33:40.511Z

## Git (*):
0a479ad6d57abfc7c6d49d0ef96373c9c047c514 (HEAD)

**Comment by AinuX** [comment]
fixed in version 2.23.2
