### ISSUE TITLE
[Crash] Error: Unknown chainId: 1. It might too early to access network state.

### ISSUE THREAD

**Issue by Library02CB** [DimensionDev/Maskbook#11219]
I was *doing something...*, then Mask reports an error.

> Unknown chainId: 1. It might too early to access network state.

Error stack:

<pre>Error: Unknown chainId: 1. It might too early to access network state.
    at SolanaChainResolverAPI.getDescriptorRequired (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/371.js:10614:32)
    at ChainResolverAPI_Base.networkType (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/371.js:10602:44)
    at useAvailableTraderProviders (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/chunk.696.js:6994:46)
    at useAllTradeComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/chunk.696.js:7226:28)
    at useAllProviderTradeContext (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/chunk.9178.js:7252:115)
    at Provider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/8201.js:4092:17)
    at Hf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:117:143)
    at Ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:278:338)
    at yk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:264:321)
    at xk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:262:30)
    at cf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:261:312)
    at df (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:256:94)
    at af (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:111:283)
    at $e (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:112:408)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/bundled/npm.react-dom.js:114:276</pre>

## Build info
- Version: 2.23.11
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: 2023-11-20T09:48:15.271Z

## Git (*):
997ce512bb026656fc7faa2dabc7f32bd48af95b (HEAD)

**Comment by Jack-Works** [comment]
looks like there is some race condition... cc @guanbinrui
