### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'network')

### ISSUE THREAD

**Issue by ChinaYangKun** [DimensionDev/Maskbook#11655]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'network')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'network')
    at https://firefly-staging.mask.social/_next/static/chunks/1705.57dee24134709bb4.js:1:1642
    at Array.filter (<anonymous>)
    at https://firefly-staging.mask.social/_next/static/chunks/1705.57dee24134709bb4.js:1:1618
    at Object.useMemo (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:49871)
    at t.useMemo (https://firefly-staging.mask.social/_next/static/chunks/6426-6df11ae87bccaf26.js:1:111279)
    at d (https://firefly-staging.mask.social/_next/static/chunks/1705.57dee24134709bb4.js:1:1604)
    at s (https://firefly-staging.mask.social/_next/static/chunks/7615.4445ea3ebca8aea9.js:1:23266)
    at i (https://firefly-staging.mask.social/_next/static/chunks/7615.4445ea3ebca8aea9.js:1:22504)
    at l (https://firefly-staging.mask.social/_next/static/chunks/7615.4445ea3ebca8aea9.js:1:22915)
    at aT (https://firefly-staging.mask.social/_next/static/chunks/6799.08f5910a001f8c3e.js:1:80313)
    at rk (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:40398)
    at iB (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:116407)
    at o4 (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:94660)
    at https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:94482
    at o3 (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:94489)
    at oQ (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:91976)
    at n2 (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:37410)
    at n4 (https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:38145)
    at https://firefly-staging.mask.social/_next/static/chunks/0347fe88-e5efe9bda5350398.js:1:39179</pre>

## Build info
- Version: unknown
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: unknown

**Comment by Jack-Works** [comment]
do you have a source map? it's impossible to read what component did this.
