### ISSUE TITLE
[Crash] RangeError: Invalid time value

### ISSUE THREAD

**Issue by lebraat** [DimensionDev/Maskbook#11878]
I was posting a link to my Gitcoin Grantee project page, then Mask reports an error.

> Invalid time value

Error stack:

<pre>RangeError: Invalid time value
    at format (/entry/contentScript.js:957:53854)
    at PreviewCard (/bundled/142.js:65:7217)
    at renderWithHooks (/bundled/55.js:36:87251)
    at updateFunctionComponent (/bundled/55.js:36:134043)
    at beginWork (/bundled/55.js:36:159586)
    at performUnitOfWork (/bundled/55.js:36:259444)
    at workLoopSync (/bundled/55.js:36:256829)
    at renderRootSync (/bundled/55.js:36:256327)
    at recoverFromConcurrentError (/bundled/55.js:36:248201)
    at performConcurrentWorkOnRoot (/bundled/55.js:36:246429)</pre>

## Build info
- Version: 2.27.0
- NODE_ENV: production
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
- build: stable
- BUILD_DATE: 2024-10-12T06:40:42.972Z

## Git (*):
8d038b7939f2b555610dc0fa0b48d43086911fb9 (HEAD)

**Comment by AinuX** [comment]
Thank you for your feedback. Could you please provide the link you pasted so we can analyze and troubleshoot the issue? Thank you!
