### ISSUE TITLE
[Crash] TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by AndiNR** [DimensionDev/Maskbook#2025]
I was ________, then Maskbook report an error.

> Cannot read property 'replace' of undefined

Error stack:
<pre>TypeError: Cannot read property 'replace' of undefined
    at Object.strip0x (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.chunk.js:6376:16)
    at isValidFormat (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.chunk.js:188:21)
    at Function.isValid (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.wallet.ts.chunk.js:150:14)
    at createContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:1397:68)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:1490:72
    at Object.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:183:60)
    at push.1048.exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react.chunk.js:76:414)
    at useContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:1490:65)
    at useBalanceCheckerContract (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/options-page.js:1738:54)
    at useTokensBalance (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/options-page.js:1754:36)</pre>

## Build information:

- Version: 1.20.1
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-03T16:27:22.741Z
- VERSION: v1.20.0-7-gfffb121b

## Git (*):

fffb121b (released) on tag "v1.20.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
@guanbinrui @septs @Jack-Works

**Comment by septs** [comment]
Note:
https://github.com/petejkim/wallet.ts/search?q=strip0x
https://github.com/DimensionDev/Maskbook/search?q=createContract

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/2200ba093a0c637ccf4f504f2374181d91c4d6de/packages/maskbook/src/web3/contracts/useBalanceChecker.ts#L8-L11

@guanbinrui chain id, may be is unexpected.

**Comment by AndiNR** [comment]
always error if switch from metamask wallet to maskbook wallet

**Comment by guanbinrui** [comment]
> always error if switch from metamask wallet to maskbook wallet

Hi @AndiNR What chain are u using in Metamask?

**Comment by AndiNR** [comment]
> Hi @AndiNR What chain are u using in Metamask? It may cause by an unknown chain id was used. We have shipped new ver with Non-Mainnet chain id prohibited.

I think binance smart chain .

**Comment by guanbinrui** [comment]
I'm going to close this now. Feel free to open it again for future problems.

**Comment by Tedko** [comment]
duplicate; fixed by #2263
