### ISSUE TITLE
[Crash] TypeError: Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2029]
<img width="1503" alt="Screen Shot 2020-12-05 at 05 09 04" src="https://user-images.githubusercontent.com/6687437/101215059-12aad500-36b8-11eb-8ebc-1c3546153360.png">

I was ___trying to swap $ to some $ at search page_____, then Maskbook report an error.

> Cannot read property 'currency' of undefined

Error stack:
<pre>TypeError: Cannot read property 'currency' of undefined
    at Function.swapCallParameters (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.uniswap.chunk.js:1439:37)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14772:39
    at Object.Yh [as useMemo] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:179:444)
    at push.1048.exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react.chunk.js:76:414)
    at useSwapParameters (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14767:36)
    at useTradeCallback_useTradeCallback (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14816:29)
    at trader_useTradeCallback_useTradeCallback (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:14900:21)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:15536:61)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:167:137)
    at gi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:191:158)</pre>

## Build information:

- Version: 1.20.1
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-03T16:27:22.741Z
- VERSION: v1.20.0-7-gfffb121b

## Git (*):

fffb121b (released) on tag "v1.20.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
cc @septs @Jack-Works @zhouhanseng take a look

**Comment by guanbinrui** [comment]
> cc @septs @Jack-Works @zhouhanseng take a look

I will handle this in ver 1.21.1

**Comment by Tedko** [comment]
@guanbinrui Assume this is fixed?

**Comment by guanbinrui** [comment]
Fail to reproduce, feel free to reopen if someone can reproduce it.
