### ISSUE TITLE
[Crash] Error: Unreachable case:64

### ISSUE THREAD

**Issue by Kqryptic** [DimensionDev/Maskbook#2094]
I was __login ______, then Maskbook report an error.

> Unreachable case:64

Error stack:
<pre>Error: Unreachable case:64
    at unreachable (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:768:11)
    at resolveLinkOnEtherscan (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:19997:85)
    at WalletStatusDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:3456:179)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:167:137)
    at gi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:191:158)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:288:475)
    at bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:269:22)
    at ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:439)
    at Sj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:299)
    at Kj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:261:163)</pre>

## Build information:

- Version: 1.21.2
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-09T05:54:56.384Z
- VERSION: v1.21.2

## Git ():

6c9967ec (released) on tag "v1.21.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
@guanbinrui u can use safeUnreachable for case that we only blocks compile but not throw in the runtime

**Comment by Tedko** [comment]
not sure if related #2029

**Comment by Tedko** [comment]
@guanbinrui is this fixed?

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/bb7353bc531bdf108349982cab9d8110d3227dcc/packages/maskbook/src/web3/pipes.ts#L68-L83

**Comment by Jack-Works** [comment]
question: how is it possible to receive an unknown ETH chain? does it comes from outer world (e.g. MetaMask)?

**Comment by Tedko** [comment]
> question: how is it possible to receive an unknown ETH chain? does it comes from outer world (e.g. MetaMask)?

Likely. MM can add customized chain for testing... might be the reason.
@guanbinrui thoughts? this bug seems is  not fixed yet

**Comment by Tedko** [comment]
https://github.com/DimensionDev/Maskbook/issues/2025#issuecomment-739940902

@septs @guanbinrui 

Thats the reason. FYI https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain

We dont need to support these customized chains like B-SC; but need to make sure that it did not throw error on our end...

**Comment by Tedko** [comment]
duplicate; fixed by https://github.com/DimensionDev/Maskbook/issues/2263
