### ISSUE TITLE
[Crash] SyntaxError: Cannot convert 511923.490995555688 to a BigInt

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2118]
I was ___trying to swap $mtsla ; change the $eth -> $mtsla  to  $usdt -> $mtsla_____, then Maskbook report an error.

> Cannot convert 511923.490995555688 to a BigInt

Error stack:
<pre>SyntaxError: Cannot convert 511923.490995555688 to a BigInt
    at Function.value (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jsbi.chunk.js:6:7264)
    at toUniswapCurrencyAmount (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:166:102)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:15886:126
    at Object.Yh [as useMemo] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:179:444)
    at push.1047.exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react.chunk.js:76:414)
    at useBestTradeExactIn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:15883:36)
    at useV2Trade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:15867:30)
    at useTradeComputed_useTradeComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:16096:22)
    at useTradeStateComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:16128:27)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:16216:127)</pre>

## Build information:

- Version: 1.22.1
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-15T06:07:31.636Z
- VERSION: v1.22.1

## Git ():

b5cf9fa2 (released) on tag "v1.22.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
<img width="1354" alt="Screen Shot 2020-12-17 at 02 34 39" src="https://user-images.githubusercontent.com/6687437/102391322-84681480-4010-11eb-8a9d-9702c4a8b5f3.png">

**Comment by Tedko** [comment]
@guanbinrui @zhouhanseng @Jack-Works prioritize this one

**Comment by Tedko** [comment]
How to reproduce 

https://imgur.com/a/ShQVhTi

**Comment by Jack-Works** [comment]
Maybe use BigNumber instead of BigInt🤔

**Comment by Tedko** [comment]
> Maybe use BigNumber instead of BigInt🤔

yeah helpful
