### ISSUE TITLE
[Crash] TypeError: Cannot read property 'transactionHash' of undefined

### ISSUE THREAD

**Issue by Miaommmisokay** [DimensionDev/Maskbook#2148]
I was ________, then Maskbook report an error.

> Cannot read property 'transactionHash' of undefined

Error stack:
<pre>TypeError: Cannot read property 'transactionHash' of undefined
    at TransactionDialogUI (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/background-service-content-script-options-page-popup.chunk.js:2843:280)
    at wh (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:167:137)
    at gi (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:191:158)
    at ck (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:288:475)
    at bk (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:269:22)
    at ak (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:268:439)
    at Sj (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:268:299)
    at Kj (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:261:163)
    at chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.react-dom.chunk.js:131:115
    at push.1128.exports.unstable_runWithPriority (chrome-extension://kgaidcihhdceepbaglflcghigenjbbbp/js/npm.scheduler.chunk.js:36:343)</pre>

## Build information:

- Version: 1.22.0
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: beta
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2020-12-27T09:57:41.999Z
- VERSION: v1.21.4-135-gf1c45ae0

## Git (*):

f1c45ae0 (feature/ito) on tag "v1.22.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by Miaommmisokay** [comment]
![6351609142135_ pic_hd](https://user-images.githubusercontent.com/42923688/103199158-2cd97b00-4925-11eb-81e6-4ae435b36eb5.jpg)

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/16af534175f7453ff512b59f5baea59806a13bcb/packages/maskbook/src/web3/UI/TransactionDialog.tsx#L123-L129

CC @guanbinrui

**Comment by septs** [comment]
The bug Introduced by ITO plugin (#1978)
