### ISSUE TITLE
[Crash] SyntaxError: Invalid regular expression: /C************9@gmail.com/: Nothing to repeat

### ISSUE THREAD

**Issue by script-money** [DimensionDev/Maskbook#2204]
I was script.money, then Maskbook report an error.

> Invalid regular expression: /C************9@gmail.com/: Nothing to repeat

Error stack:
<pre>SyntaxError: Invalid regular expression: /C************9@gmail.com/: Nothing to repeat
    at String.search (<anonymous>)
    at parseText (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:19857:44)
    at RenderText (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/background-service-content-script-options-page-popup.chunk.js:19828:76)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:167:137)
    at gi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:191:158)
    at fi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:189:173)
    at di (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:188:178)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:293:427)
    at bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:269:22)
    at ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.chunk.js:268:439)</pre>

## Build information:

- Version: 1.22.3
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: undefined
- resolution: desktop
- BUILD_DATE: 2021-01-05T14:51:07.482Z
- VERSION: v1.22.3

## Git ():

012251c5 (released) on tag "v1.22.3"
git@github.com:DimensionDev/Maskbook.git

source tweets: https://twitter.com/CoinDCX/status/1347423525175377923

**Comment by Jack-Works** [comment]
Interesting problem, it seems like we use text as an regex somewhere and with a email that not a valid regexp it throws
