### ISSUE TITLE
[Crash] Error: Unreachable case:80

### ISSUE THREAD

**Issue by xh0106** [DimensionDev/Maskbook#2233]
I was ________, then Mask report an error.

> Unreachable case:80

Error stack:
<pre>Error: Unreachable case:80
    at unreachable (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/options-page.js:8787:11)
    at resolveLinkOnEtherscan (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/76.js:20326:80)
    at WalletStatusDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/76.js:16142:161)
    at wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:227:137)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:347:49)
    at bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:329:22)
    at ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:328:439)
    at Sj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:328:299)
    at Mj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:317:493)
    at W (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.scheduler.js:21:197)</pre>

## Build information:

- Version: 1.23.2
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-01-10T05:21:55.725Z
- VERSION: v1.23.2

## Git ():

c86ff7f6 (released) on tag "v1.23.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
Duplicate of #2094
