### ISSUE TITLE
[Crash] Error: initCodeHash must be 32 bytes (argument="initCodeHash", value="", code=INVALID_A...

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2391]
I was ____try to swap; 1000 dai -> some token; then switch provider from 0x to univ2____, then Mask report an error.

<img width="1371" alt="Screen Shot 2021-02-14 at 00 47 09" src="https://user-images.githubusercontent.com/6687437/107855580-434c7f00-6e5e-11eb-877e-ec21afec30c4.png">

> initCodeHash must be 32 bytes (argument="initCodeHash", value="", code=INVALID_ARGUMENT, version=address/5.0.9)

Error stack:
<pre>Error: initCodeHash must be 32 bytes (argument="initCodeHash", value="", code=INVALID_ARGUMENT, version=address/5.0.9)
    at Logger.makeError (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:4841:23)
    at Logger.throwError (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:4850:20)
    at Logger.throwArgumentError (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:4853:21)
    at getCreate2Address (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:3165:16)
    at getPairAddress (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:49345:75)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:43730:53
    at Array.map (<anonymous>)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:43727:27
    at Object.Yh [as useMemo] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:239:444)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/3815.js:351:414)</pre>

## Build information:

- Version: 1.27.1
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-02-03T10:37:11.945Z
- VERSION: v1.27.1-1-gdb3bcf05

## Git (*):

db3bcf05 (released) on tag "v1.27.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
seems this is fixed alredy at https://github.com/DimensionDev/Maskbook/issues/2346
v1.27.4

btw - why the chrome store review is stucked ?? @guanbinrui

**Comment by Tedko** [comment]
closed. duplicate
