### ISSUE TITLE
[Crash] NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node i...

### ISSUE THREAD

**Issue by 7bucher7** [DimensionDev/Maskbook#2411]
I was ________, then Mask report an error.

> Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error stack:
<pre>Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at dj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:305:93)
    at dj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:305:168)
    at bj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:303:129)
    at dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:335:277)
    at exports.unstable_runWithPriority (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:28369:343)
    at $f (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:190:325)
    at Tj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:331:295)
    at Mj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:319:364)
    at W (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:28367:197)
    at MessagePort.G.port1.onmessage (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5695.js:28364:296)</pre>

## Build information:

- Version: 1.27.4
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-02-12T16:23:34.721Z
- VERSION: v1.27.4

## Git ():

0c4e8f59 (released) on tag "v1.27.4"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
interesting problem @7bucher7 can you tell us what you're doing leads to the crash? that may help, thanks

**Comment by Tedko** [comment]
yo anyone can reproduce?

**Comment by Jack-Works** [comment]
sorry we have no enough info to reproduce problem
