### ISSUE TITLE
[Crash] TypeError: Cannot read property 'toPrecision' of undefined

### ISSUE THREAD

**Issue by bigzenos** [DimensionDev/Maskbook#2476]
I was *doing something...*, then Mask report an error.

> Cannot read property 'toPrecision' of undefined

Error stack:

<pre>TypeError: Cannot read property 'toPrecision' of undefined
    at formatCurrency (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5997.js:52203:69)
    at TrendingViewDeck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5997.js:49406:113)
    at Yh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:234:137)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:96)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:370)
    at vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:230)
    at nk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:335:163)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:138:115
    at exports.unstable_runWithPriority (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5997.js:28692:416)</pre>

## Build info
- Version: 1.29.2
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-02-23T10:43:34.700Z
- VERSION: v1.29.1-6-g4346fdaa

## Git ():

4346fdaa (released) on tag "v1.29.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/b268e8dd8aa75fa3ebd49df86d96b97cef8fa32b/packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx#L278-L283

CC @guanbinrui
