### ISSUE TITLE
[Crash] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by yuandan9** [DimensionDev/Maskbook#2580]
I was *doing something...*, then Mask report an error.

> Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error stack:

<pre>Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Gj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:317:80)
    at Qj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:322:112)
    at Ik (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:346:38)
    at exports.unstable_runWithPriority (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7589.js:28463:416)
    at pd (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:137:325)
    at wk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:436)
    at pk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:334:167)
    at I (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7589.js:28460:203)
    at MessagePort.Q.port1.onmessage (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7589.js:28461:174)</pre>

## Build info
- Version: 1.29.10
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-03-12T13:41:21.559Z
- VERSION: v1.29.10

## Git ():

e64f4437 (released) on tag "v1.29.10"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/e64f44372a6af43d3c0499c5d54e58b618506c2f/packages/maskbook/src/utils/shadow-root/usePortalShadowRoot.tsx#L32-L42

**Comment by Jack-Works** [comment]
@yuandan9 hi what are you doing when this error appears? In which position it appears?

**Comment by Jack-Works** [comment]
sorry we do not have enough information to investigate this crash
