### ISSUE TITLE
[Crash] Error: Invalid Username （strange bug with red package)

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2626]
https://twitter.com/suji_yan/status/1221326164213452801

<img width="1217" alt="Screen Shot 2021-03-20 at 00 59 40" src="https://user-images.githubusercontent.com/6687437/111816412-c78b9980-8917-11eb-96e0-83bd411c546d.png">

I was *doing something...*, then Mask report an error.

> Invalid Username

Error stack:

<pre>Error: Invalid Username
    at getPostUrlAtTwitter (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2922.js:760:15)
    at getPostUrl (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:38914:55)
    at RedPacketInPost (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:38935:67)
    at Yh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:234:137)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:96)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:370)
    at vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:230)
    at nk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:335:260)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:138:115</pre>

## Build info
- Version: 1.29.12
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-03-16T07:10:01.875Z
- VERSION: v1.29.12

## Git ():

0b4ce587 (released) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
strange bug. introduced in our recent ver? @guanbinrui @Jack-Works @zhouhanseng

**Comment by guanbinrui** [comment]
![image](https://user-images.githubusercontent.com/52657989/111938243-86a4a800-8b04-11eb-888e-69628e169bc5.png)

**Comment by guanbinrui** [comment]
@zhouhanseng Take a look?

**Comment by zhouhanseng** [comment]
Close by https://github.com/DimensionDev/Maskbook/pull/2605/commits/2a24778dfc19618579520bc18852762e4be8be79

Remove the unexpected date from userId.
