### ISSUE TITLE
[Crash] Error: Invalid Username

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#2765]
![14361617704114_ pic_hd](https://user-images.githubusercontent.com/6687437/113696009-113ff680-9704-11eb-8a03-bc5a705e29e0.jpg)

I was *doing something...*, then Mask report an error.

> Invalid Username

Error stack:

<pre>Error: Invalid Username
    at getPostUrlAtTwitter (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2922.js:760:15)
    at getPostUrl (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:38893:55)
    at RedPacketInPost (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:38914:67)
    at Yh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:234:137)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:96)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:370)
    at vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:230)
    at pk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:332:500)
    at I (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:26516:203)</pre>

## Build info
- Version: 1.29.13
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-03-24T07:13:04.021Z
- VERSION: v1.29.13

## Git ():

6b48e8bd (released) on tag "v1.29.13"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
tested. confirm -fixed.
