### ISSUE TITLE
[Crash] TypeError: Cannot read property 'cssRules' of null

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#2834]
I was *doing something...*, then Mask report an error.

> Cannot read property 'cssRules' of null

Error stack:

<pre>TypeError: Cannot read property 'cssRules' of null
    at getValidRuleInsertionIndex (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jss.js:1766:28)
    at DomRenderer.insertRule (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jss.js:1913:26)
    at DomRenderer.insertRules (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jss.js:1875:12)
    at DomRenderer.deploy (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jss.js:1862:12)
    at StyleSheet.deploy (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jss.js:1204:38)
    at StyleSheet.attach (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jss.js:1083:30)
    at attach (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.material-ui.styles.js:632:18)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.material-ui.styles.js:744:7
    at useSynchronousEffect (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.material-ui.styles.js:698:14)
    at useStyles (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.material-ui.styles.js:736:5)</pre>

## Build info
- Version: 1.30.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-04-14T13:57:52.772Z
- VERSION: v1.29.12-204-geea040a8

## Git ():

eea040a8 (released) on tag "v1.30.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by guanbinrui** [comment]
One more case: https://twitter.com/chrismessina/status/1382748536828141570

![tttt123](https://user-images.githubusercontent.com/52657989/115051691-ae263f00-9f0f-11eb-928c-582cb3a9e886.png)

**Comment by Jack-Works** [comment]
I have to say it's almost impossible to fix because it actually a race condition involves so many different parts (Twitter, our watchers, AbortSignal, React and delay on hook effects).

**Comment by guanbinrui** [comment]
> I have to say it's almost impossible to fix because it actually a race condition involves so many different parts (Twitter, our watchers, AbortSignal, React and delay on hook effects).

I'm afraid that it was introduced by the new version.

**Comment by Jack-Works** [comment]
Does it appear often?

**Comment by guanbinrui** [comment]
> Does it appear often?

Yes, it's reproducible. Try https://twitter.com/search?q=%24dai&src=typed_query

**Comment by Jack-Works** [comment]
Ok I'll take that

**Comment by Jack-Works** [comment]
Oops. it seems like this problem gets serious.
