### ISSUE TITLE
[Crash] Error: Invalid Username

### ISSUE THREAD

**Issue by lhfly5201314** [DimensionDev/Maskbook#2861]
I was *doing something...*, then Mask report an error.

> Invalid Username

Error stack:

<pre>Error: Invalid Username
    at getPostUrlAtTwitter (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2922.js:760:15)
    at getPostUrl (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:38893:55)
    at RedPacketInPost (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:38914:67)
    at Yh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:234:137)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:96)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:370)
    at vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:230)
    at pk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:332:500)
    at I (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/718.js:26516:203)</pre>

## Build info
- Version: 1.29.13
- NODE_ENV: production
- STORYBOOK: false
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-03-24T07:13:04.021Z
- VERSION: v1.29.13

## Git ():

6b48e8bd (released) on tag "v1.29.13"
git@github.com:DimensionDev/Maskbook.git

**Comment by yisiliu** [comment]
@lhfly5201314 hi thanks for reporting this bug! Can you please try to update to the latest version (v1.30.4) and see if the bug stays?

**Comment by lhfly5201314** [comment]
Cool,it works now.But the red racket is empty...

**Comment by guanbinrui** [comment]
Fixed in the new version (v1.30.4).
