### ISSUE TITLE
[Crash] Error: Minified React error #321

### ISSUE THREAD

**Issue by triple3d** [DimensionDev/Maskbook#3108]
I was *doing something...*, then Mask report an error.

> Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error stack:

<pre>Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Wh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:233:238)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/content-script.js:141:450)
    at useObservableValues (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/4671.js:9947:43)
    at usePostInfoDetails (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/9839.js:937:16)
    at PostInspector (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.9881.js:23279:66)
    at Yh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:234:137)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:96)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:370)
    at vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:230)</pre>

## Build info
- Version: 1.32.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-05-07T15:13:35.015Z
- VERSION: v1.29.12-304-g771aa1a1

## Git ():

771aa1a1 (released) on tag "v1.32.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
@triple3d thanks for your report! can you describe what are you doing, or what post are you viewing when the error occurs? And, is this error appear often? Does the retry button works?
