### ISSUE TITLE
[Crash] NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by PAKISTANECN1** [DimensionDev/Maskbook#3165]
I was *doing something...*, then Mask report an error.

> Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error stack:

<pre>Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Lj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:315:93)
    at Lj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:315:168)
    at Jj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:313:115)
    at Qj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:322:465)
    at Ik (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:346:38)
    at exports.unstable_runWithPriority (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/3380.js:290:416)
    at pd (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:137:325)
    at wk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:436)
    at pk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:334:167)
    at I (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/3380.js:287:203)</pre>

## Build info
- Version: 1.32.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-05-07T15:13:35.015Z
- VERSION: v1.29.12-304-g771aa1a1

## Git ():

771aa1a1 (released) on tag "v1.32.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
hi, @PAKISTANECN1 thanks for your report. is that a bug that occurs often? what are you doing when the error happened?

**Comment by PAKISTANECN1** [comment]
> привет, @ PAKISTANECN1 благодарим за отчет. это ошибка, которая часто встречается? что вы делаете, когда произошла ошибка?

Приветствую Джек . Ошибка возникает при переходе из одного узла к другому , встречается не везде , но частенько на некоторых сайтах связанных с прозрачностью и метаданными .

**Comment by Jack-Works** [comment]
Sorry I cannot understand your meaning even I use a translator. 😢

**Comment by septs** [comment]
@AinuX plz follow this "bug"

**Comment by AinuX** [comment]
Can't reproduce this issue with build 1.34, please try it with latest build, thanks!
