### ISSUE TITLE
[Crash] Error: Component must be wrapped with <Container.Provider>

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3221]
When claim ITO swapped token, report the following error.

 Component must be wrapped with <Container.Provider>

Error stack:

<pre>Error: Component must be wrapped with <Container.Provider>
    at Object.useContainer (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1220.js:28062:13)
    at EthereumWalletConnectedBoundary (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1220.js:26563:143)
    at Yh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:234:137)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:96)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:370)
    at vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:230)
    at pk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:332:500)
    at I (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2404.js:7606:203)
    at MessagePort.Q.port1.onmessage (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2404.js:7607:174)</pre>

## Build info
- Version: 1.32.2
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-05-24T06:04:26.310Z
- VERSION: v1.29.12-366-g09744498

## Git (*):

09744498 (septs/update-ko-language) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git

**Comment by AinuX** [comment]
<!--Thanks for the crash report!

When claim ITO swapped token, report the following error.

> Component must be wrapped with <Container.Provider>

Error stack:

<pre>Error: Component must be wrapped with <Container.Provider>
    at Object.useContainer (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1220.js:28062:13)
    at EthereumWalletConnectedBoundary (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1220.js:26563:143)
    at Yh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:234:137)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:96)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:370)
    at vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:230)
    at pk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:332:500)
    at I (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2404.js:7606:203)
    at MessagePort.Q.port1.onmessage (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2404.js:7607:174)</pre>

## Build info
- Version: 1.32.2
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-05-24T06:04:26.310Z
- VERSION: v1.29.12-366-g09744498

## Git (*):

09744498 (septs/update-ko-language) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git
