### ISSUE TITLE
[Crash] TypeError: Cannot read property 'useContext' of null

### ISSUE THREAD

**Issue by UncleBill** [DimensionDev/Maskbook#3270]
I was *doing something...*, then Mask report an error.

> Cannot read property 'useContext' of null

Error stack:

<pre>TypeError: Cannot read property 'useContext' of null
    at Object.useContext (npm:react/cjs/react.development.js:1519:21)
    at useTheme (npm:@material-ui/private-theming/useTheme/useTheme.js:10:52)
    at useStyles (npm:@material-ui/styles/makeStyles/makeStyles.js:233:69)
    at SnackbarContainer (npm:notistack/dist/notistack.esm.js:689:17)
    at renderWithHooks (npm:react-dom/cjs/react-dom.development.js:15849:18)
    at updateFunctionComponent (npm:react-dom/cjs/react-dom.development.js:18729:20)
    at updateSimpleMemoComponent (npm:react-dom/cjs/react-dom.development.js:18478:10)
    at updateMemoComponent (npm:react-dom/cjs/react-dom.development.js:18355:14)
    at beginWork (npm:react-dom/cjs/react-dom.development.js:20760:16)
    at beginWork$1 (npm:react-dom/cjs/react-dom.development.js:26280:14)</pre>

## Build info
- Version: 1.32.3
- NODE_ENV: development
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-05-30T05:27:50.946Z
- VERSION: v1.29.12-394-g093bb1392-dirty

## Git (*):

093bb1392 (feature/revamp-bsc) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git

**Comment by Himself65** [comment]
```bash
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 
    at WithStyles (webpack-internal:///../../node_modules/.pnpm/@material-ui+styles@5.0.0-alpha.33_b74978b982ba5eb1adbd094956fcb2eb/node_modules/@material-ui/styles/withStyles/withStyles.js:70:21)
    at InnerThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui+core@5.0.0-alpha.34_d5bd3f867b63568c23fe18f941426960/node_modules/@material-ui/core/styles/ThemeProvider.js:22:67)
    at ThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui+private-theming@5.0.0-alpha.33_5bdfd25fd8ef2d51cc63f093d595e68c/node_modules/@material-ui/private-theming/ThemeProvider/ThemeProvider.js:48:5)
    at ThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui+core@5.0.0-alpha.34_d5bd3f867b63568c23fe18f941426960/node_modules/@material-ui/core/styles/ThemeProvider.js:42:5)
    at StylesProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui+styles@5.0.0-alpha.33_5bdfd25fd8ef2d51cc63f093d595e68c/node_modules/@material-ui/styles/StylesProvider/StylesProvider.js:52:5)
    at StyledEngineProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui+styled-engine@5.0.0-alpha.34_cc1f12647fb33258761b006867375e84/node_modules/@material-ui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:24:5)
    at SnackbarProvider (webpack-internal:///../../node_modules/.pnpm/notistack@1.0.9/node_modules/notistack/dist/notistack.esm.js:726:24)
    at ErrorBoundary (webpack-internal:///../theme/src/Components/ErrorBoundary/ErrorBoundary.tsx:27:9)
    at I18nextProvider (webpack-internal:///../../node_modules/.pnpm/react-i18next@11.9.0_2635c239ba114560d1912f72960bc90a/node_modules/react-i18next/dist/es/I18nextProvider.js:10:19)
    at Provider (webpack-internal:///../../node_modules/.pnpm/unstated-next@1.1.0/node_modules/unstated-next/dist/unstated-next.mjs:13:31)
    at Web3Provider (webpack-internal:///../web3-shared/src/context/index.tsx:64:134)
    at BrowserActionRoot (webpack-internal:///./src/extension/browser-action/UI.tsx:152:63)
    at ErrorBoundary (webpack-internal:///../theme/src/Components/ErrorBoundary/ErrorBoundary.tsx:27:9)
```

**Comment by Himself65** [comment]
I think there are bugs in #3259

**Comment by Himself65** [comment]
https://github.com/DimensionDev/Maskbook/blob/5f2402869c5e6300d4bbc44a32ee5bbe1d1dafe8/package.json#L44-L45

https://github.com/DimensionDev/Maskbook/commit/4f90d108477a98209620826609c745d89e495b84#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R44-R45
