### ISSUE TITLE
[Crash] TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#3309]
I was *doing something...*, then Mask report an error.

> Cannot read property 'code' of undefined

Error stack:

<pre>TypeError: Cannot read property 'code' of undefined
    at ITO (./src/plugins/ITO/UI/ITO.tsx:244:103)
    at renderWithHooks (npm:react-dom/cjs/react-dom.development.js:15849:18)
    at updateFunctionComponent (npm:react-dom/cjs/react-dom.development.js:18729:20)
    at beginWork (npm:react-dom/cjs/react-dom.development.js:20688:16)
    at beginWork$1 (npm:react-dom/cjs/react-dom.development.js:26280:14)
    at performUnitOfWork (npm:react-dom/cjs/react-dom.development.js:25443:12)
    at workLoopSync (npm:react-dom/cjs/react-dom.development.js:25353:5)
    at renderRootSync (npm:react-dom/cjs/react-dom.development.js:25317:7)
    at performConcurrentWorkOnRoot (npm:react-dom/cjs/react-dom.development.js:24725:22)
    at workLoop (npm:scheduler/cjs/scheduler.development.js:253:34)</pre>

## Build info
- Version: 1.33.0
- NODE_ENV: development
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-06-09T00:54:49.662Z
- VERSION: v1.29.12-421-g4eb0d0e0b-dirty

## Git (*):

4eb0d0e0b (bugfix/ito-geolocation) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
i have this lambda timeout 3s update to 10s.
