### ISSUE TITLE
[Crash] Error: Minified React error #185

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3332]
I was *doing something...*, then Mask report an error.

> Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error stack:

<pre>Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jg (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:327:279)
    at Oh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:246:121)
    at ref (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/content-script.js:1094:312)
    at $i (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:299:183)
    at gj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:305:426)
    at pj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:319:5)
    at tj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:321:124)
    at hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:346:41)
    at Wj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:62)
    at Nj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:334:327)</pre>

## Build info
- Version: 1.33.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-06-10T18:01:41.208Z
- VERSION: v1.29.12-431-g2ac3f721

## Git (*):

2ac3f721 (master) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by Jack-Works** [comment]
Interesting problem. But the error stack doesn't help. @wenluomask what were you doing when the error occurs?

**Comment by wenluomask** [comment]
![截屏2021-06-11 下午6 19 20](https://user-images.githubusercontent.com/85149605/121987721-9feb8680-cdcb-11eb-87f0-220992b996ac.png)
I was posting the ITO, here is the screenshot of the error occurs. Now I’m the tweet is back to normal.

**Comment by septs** [comment]
@wenluomask plz provide this twitter tweet url.

**Comment by wenluomask** [comment]
https://twitter.com/WenLuo04001516/status/1403295373603446784
