### ISSUE TITLE
[Crash] TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by exploringeth** [DimensionDev/Maskbook#3348]
I was *doing something...*, then Mask report an error.

> Cannot read property 'toLowerCase' of undefined

Error stack:

<pre>TypeError: Cannot read property 'toLowerCase' of undefined
    at isSameAddress (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8166.js:4137:42)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8814.js:28268:58
    at Array.sort (<anonymous>)
    at useAssetsMerged (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8814.js:28258:133)
    at useAssets (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8814.js:28336:28)
    at GasNowDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8814.js:12106:69)
    at Oh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:236:137)
    at zi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:264:69)
    at sk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:361:403)
    at rk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:348:22)</pre>

## Build info
- Version: 1.33.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-06-06T15:02:29.930Z
- VERSION: v1.29.12-418-gec309996

## Git ():

ec309996 (released) on tag "v1.33.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/38d4098c102c908e65ab245c954cf83a50aac8a3/packages/maskbook/src/plugins/Ethereum/UI/GasNowDialog.tsx#L106
https://github.com/DimensionDev/Maskbook/blob/38d4098c102c908e65ab245c954cf83a50aac8a3/packages/maskbook/src/plugins/Wallet/hooks/useAssets.ts#L38
https://github.com/DimensionDev/Maskbook/blob/38d4098c102c908e65ab245c954cf83a50aac8a3/packages/maskbook/src/plugins/Wallet/hooks/useAssetsMerged.ts#L25-L29

**Comment by guanbinrui** [comment]
@zhouhanseng Take a look.

**Comment by zhouhanseng** [comment]
It is caused by unsupported chain.

**Comment by septs** [comment]
@guanbinrui next release date?

**Comment by septs** [comment]
CC @AinuX this bugfix tested?
