### ISSUE TITLE
[Crash] TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3420]
I was making ITO post, I was in the confirm page of ITO and then I click x to exit the page, then Mask report an error.

> Cannot read property 'toLowerCase' of undefined

Error stack:

<pre>TypeError: Cannot read property 'toLowerCase' of undefined
    at isSameAddress (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8330.js:4188:18)
    at isNative (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8330.js:4197:12)
    at ConfirmDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1096.js:10621:65)
    at Ch (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:232:137)
    at gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:29)
    at fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:22)
    at ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:342:369)
    at Vj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:342:229)
    at Nj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:334:217)
    at hg (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:195:129)</pre>

## Build info
- Version: 1.33.1
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-06-18T04:22:36.947Z
- VERSION: v1.29.12-460-gb5f09cf7

## Git (*):

b5f09cf7 (lelenei/fix-3406) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
![截屏2021-06-18 下午5 45 26](https://user-images.githubusercontent.com/85149605/122542425-3edae180-d05d-11eb-99e6-ef3b01ff75b2.png)

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/08647ee7e1248eb94b59bdb715f552bb9c1cba15/packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx#L148

**Comment by septs** [comment]
CC @guanbinrui

**Comment by wenluomask** [comment]
This bug is known and fixed, so I closed it.
