### ISSUE TITLE
[Crash] TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3450]
Change to unsupported chain, and then try the "Swap" function.

> Cannot read property 'map' of undefined

Error stack:

<pre>TypeError: Cannot read property 'map' of undefined
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/268.js:18864:148
    at Object.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:252:347)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/90.js:54:279)
    at useAllCommonPairs (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/268.js:18864:36)
    at useV2Trade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/268.js:18934:46)
    at trader_useTradeComputed_useTradeComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/268.js:19270:22)
    at useTradeStateComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/268.js:19328:27)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/268.js:19408:127)
    at Oh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:236:137)
    at sk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:360:96)</pre>

## Build info
- Version: 1.33.2
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-06-21T06:56:15.342Z
- VERSION: v1.29.12-442-g38ed30281

## Git (*):

38ed30281 (hotfix/1.33.2) on tag "v1.33.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/38ed30281acb8c7ebcc21b6778e3d90d9b638676/packages/maskbook/src/plugins/Trader/trader/uniswap/useAllCommonPairs.ts#L10

**Comment by Tedko** [comment]
any fix?

**Comment by AinuX** [comment]
With 1.34 build, the "Swap" will hide when switch network to unsupported chain, will not see the error again.
