### ISSUE TITLE
[Crash] Error: Invariant failed

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3472]
I was *doing something...*, then Mask report an error.

> Invariant failed

Error stack:

<pre>Error: Invariant failed
    at invariant (chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/1792.js:910:15)
    at validateAndParseAddress (chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/npm-ns.uniswap.sdk.js:323:83)
    at new Token (chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/npm-ns.uniswap.sdk.js:423:21)
    at toUniswapToken (chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/114.js:17781:12)
    at chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/114.js:19275:159
    at Array.map (<anonymous>)
    at chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/114.js:19275:148
    at Object.useMemo (chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/npm.react-dom.js:248:120)
    at exports.useMemo (chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/6493.js:53:214)
    at useAllCommonPairs (chrome-extension://fhmplkcnkmcpkapnmnfckclhdnjljdhj/js/114.js:19275:36)</pre>

## Build info
- Version: 1.33.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-06-23T02:56:47.067Z
- VERSION: v1.29.12-483-g9d4560325

## Git (*):

9d4560325 (feature/swap-integration) on tag "v1.29.12"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/9d45603/packages/maskbook/src/plugins/Trader/helpers/uniswap.ts

**Comment by wenluomask** [comment]
![截屏2021-06-23 上午11 51 57](https://user-images.githubusercontent.com/85149605/123033429-54b02400-d41a-11eb-8099-4166290114e6.png)

https://user-images.githubusercontent.com/85149605/123033435-5679e780-d41a-11eb-85d2-70d79c3b72ef.mov

I create issueMASK-67 about this in Jira.

**Comment by guanbinrui** [comment]
The Uniswap only works on Mainnet and Rinkeby.
