### ISSUE TITLE
[Crash] TypeError: Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#3535]
I was *swap $eth to $dai on 0x/ sushi, then Mask report an error.

> Cannot read property 'currency' of undefined

Error stack:

<pre>TypeError: Cannot read property 'currency' of undefined
    at Function.swapCallParameters (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.uniswap.sdk.js:1426:37)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1652.js:19094:55
    at Object.ni [as useMemo] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:247:377)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7290.js:54:279)
    at useSwapParameters (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1652.js:19089:29)
    at uniswap_useTradeCallback_useTradeCallback (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1652.js:19119:29)
    at trader_useTradeCallback_useTradeCallback (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1652.js:19385:23)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1652.js:20211:61)
    at Oh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:236:137)
    at zi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:264:69)</pre>

## Build info
- Version: 1.33.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-06-29T04:12:44.763Z
- VERSION: v1.29.12-449-ged441b6d

## Git ():

ed441b6d (released) on tag "v1.33.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
how to reproduce -

1 search $eth
2 swap $eth -> $dai through 0x
3 proceed until metamask should popup to confirm (no metamask popup)

<img width="1473" alt="Screen Shot 2021-07-01 at 04 52 15" src="https://user-images.githubusercontent.com/6687437/124030226-921f3d80-da28-11eb-846f-308fcc221ffc.png">

4 switch to swap on uni/sushi - try swap. 
5 crash

**Comment by AinuX** [comment]
Fixed with build 1.34.0.
