### ISSUE TITLE
[Crash] TypeError: Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3670]
I changed to xDai network when I was selecting token in red packet dialog, then Mask report an error. There is a similar situation occurs in dashboard's wallet page.
![截屏2021-07-14 下午3 00 27](https://user-images.githubusercontent.com/85149605/125578251-cf833ff7-0dd4-40f7-9a27-f8147ea2719f.png)

> Cannot read property 'sort' of undefined

Error stack:

<pre>TypeError: Cannot read property 'sort' of undefined
    at useERC20TokensDetailedFromTokenLists (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/1607.js:5590:230)
    at FixedTokenList (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/3399.js:313:112)
    at Ch (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/npm.react-dom.js:232:137)
    at si (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/npm.react-dom.js:259:255)
    at gk (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/npm.react-dom.js:356:346)
    at fk (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/npm.react-dom.js:343:22)
    at ek (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/npm.react-dom.js:342:369)
    at Vj (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/npm.react-dom.js:342:229)
    at Pj (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/npm.react-dom.js:331:476)
    at J (chrome-extension://mjdfjmoplimielemnlncdacbceeeinke/js/2106.js:16253:203)</pre>

## Build info
- Version: 1.34.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-07-13T05:31:25.869Z
- VERSION: v1.29.12-578-gafe190040

## Git (*):

afe190040 (hotfix/1.34.1) on tag "v1.34.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/afe190040deb31a8b6181b249f34c2c452764384/packages/web3-shared/src/hooks/useERC20TokensDetailedFromTokenLists.ts#L21-L24

**Comment by Himself65** [comment]
> https://github.com/DimensionDev/Maskbook/blob/afe190040deb31a8b6181b249f34c2c452764384/packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx#L45-L52
> 
> https://github.com/DimensionDev/Maskbook/blob/afe190040deb31a8b6181b249f34c2c452764384/packages/web3-shared/src/hooks/useERC20TokensDetailedFromTokenLists.ts#L21-L24

The current development branch has been fixed. see #3684

**Comment by septs** [comment]
CC @AinuX

**Comment by wenluomask** [comment]
Checked.
