### ISSUE TITLE
[Crash] NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by PAKISTANECN1** [DimensionDev/Maskbook#3696]
I was *doing something...*, then Mask report an error.

> Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error stack:

<pre>Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at jj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:315:80)
    at tj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:320:114)
    at hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:346:41)
    at Wj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:344:62)
    at Nj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:334:327)
    at hg (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:195:129)</pre>

## Build info
- Version: 1.34.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-07-07T03:01:12.679Z
- VERSION: v1.29.12-563-g4ff9703ba

## Git ():

4ff9703ba (released) on tag "v1.34.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by AinuX** [comment]
@PAKISTANECN1 

Could you share more info about the procedure how to trigger the exception? thanks!
