### ISSUE TITLE
[Crash] TypeError: Failed to construct 'URL': Invalid base URL

### ISSUE THREAD

**Issue by AinuX** [DimensionDev/Maskbook#3709]
https://user-images.githubusercontent.com/2582974/126142912-bfc47371-5c55-459f-afe4-f517f9d89cf8.mp4

Switch network in from dHEDGE supported chain (ETH) to unsupported chain (BSC or Polygon),  and then. check the plugin card.

> Failed to construct 'URL': Invalid base URL

Error stack:

<pre>TypeError: Failed to construct 'URL': Invalid base URL
    at usePoolURL (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/6570.js:356:12)
    at PoolViewDeck (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/6570.js:766:21)
    at Ch (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/npm.react-dom.js:232:137)
    at si (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/npm.react-dom.js:259:255)
    at gk (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/npm.react-dom.js:356:346)
    at fk (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/npm.react-dom.js:343:22)
    at ek (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/npm.react-dom.js:342:369)
    at Vj (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/npm.react-dom.js:342:229)
    at Pj (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/npm.react-dom.js:331:476)
    at J (chrome-extension://oaflimfponpdajjjdlbmbjhmblpilgjf/js/8614.js:16253:203)</pre>

## Build info
- Version: 1.34.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-07-16T09:13:55.747Z
- VERSION: v1.29.12-564-gf79aa26a7

## Git (*):

f79aa26a7 (released) on tag "v1.34.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f79aa26a7945d4e68f82e4f7f54e57f7f3d01d5e/packages/maskbook/src/plugins/dHEDGE/UI/PoolViewDeck.tsx#L62-L70

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/f79aa26a7945d4e68f82e4f7f54e57f7f3d01d5e/packages/maskbook/src/plugins/dHEDGE/hooks/useUrl.ts#L4-L15

**Comment by wenluomask** [comment]
Checked.
