### ISSUE TITLE
[Crash] TypeError: Cannot read property 'toFixed' of null

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3855]
I posted a tweet included pooltogether's link, then Mask report an error.
Here is my tweet: https://twitter.com/WEN6666661/status/1423144265228587008
and i was in latest develop.

> Cannot read property 'toFixed' of null

Error stack:

<pre>TypeError: Cannot read property 'toFixed' of null
    at PoolView (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/chunk.8937.js:1600:75)
    at Ch (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/npm.react-dom.js:232:137)
    at si (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/npm.react-dom.js:259:255)
    at gk (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/npm.react-dom.js:356:346)
    at fk (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/npm.react-dom.js:343:22)
    at ek (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/npm.react-dom.js:342:369)
    at Vj (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/npm.react-dom.js:342:229)
    at Pj (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/npm.react-dom.js:331:476)
    at J (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/1528.js:19979:203)
    at MessagePort.R (chrome-extension://momgpnhedkjmcmlmmphclokcpiikhbjd/js/1528.js:19980:123)</pre>

## Build info
- Version: 1.35.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-04T13:49:50.523Z
- VERSION: v1.29.12-712-gdd9a3b596

## Git (*):

dd9a3b596 (develop) on tag "v1.35.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Checked.
