### ISSUE TITLE
[Crash] Error: invalid address

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3863]
I was checking the tweet with pooltogether link, I change to account tab, then Mask report an error.
Here is the tweet I checked: https://twitter.com/WEN6666661/status/1423146613363539980
> invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.4.0) (argument="account", value="", code=INVALID_ARGUMENT, version=abi/5.0.7)

Error stack:

<pre>Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.4.0) (argument="account", value="", code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/1528.js:3445:23)
    at Logger.throwError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/1528.js:3454:20)
    at Logger.throwArgumentError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/1528.js:3457:21)
    at AddressCoder._throwError (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:851:31)
    at AddressCoder.encode (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:977:18)
    at chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1060:19
    at Array.forEach (<anonymous>)
    at pack (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1046:12)
    at TupleCoder.encode (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1354:16)
    at AbiCoder.encode (chrome-extension://fmfgjaeiddkdhgmioobeancabcmkpfab/js/npm-ns.ethersproject.abi.js:1443:15)</pre>

## Build info
- Version: 1.35.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-05T08:14:00.707Z
- VERSION: v1.29.12-718-g00a1b682c

## Git (*):

00a1b682c (develop) on tag "v1.35.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by iRhonin** [comment]
Facing this bug on `useAccount ` hook.

**Comment by wenluomask** [comment]
Error occurs again in branch pull/3875.

**Comment by iRhonin** [comment]
@wenluomask the PR/3875 is not related to this bug, I think it is beyond pooltogether scope.

**Comment by wenluomask** [comment]
This error only occurs in matic mainnet and there is deposit in my account. Hope this will help.
