### ISSUE TITLE
[Crash] Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value="", code=INVALID_ARGUMENT, version=abi/5.0.7)

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3902]
I was checking the GoodGhosting plugin, I changed to Matic Mainnet in MetaMask since no wallet is connected, then Mask reports an error. It is similar to #3863, the tweet included GoodGhosting is https://twitter.com/WenLuo04001516/status/1423313410410782720

> invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value="", code=INVALID_ARGUMENT, version=abi/5.0.7)

Error stack:

<pre>Error: invalid address (argument="address", value="", code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value="", code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/9098.js:3445:23)
    at Logger.throwError (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/9098.js:3454:20)
    at Logger.throwArgumentError (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/9098.js:3457:21)
    at AddressCoder._throwError (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/npm-ns.ethersproject.abi.js:851:31)
    at AddressCoder.encode (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/npm-ns.ethersproject.abi.js:977:18)
    at chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/npm-ns.ethersproject.abi.js:1060:19
    at Array.forEach (<anonymous>)
    at pack (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/npm-ns.ethersproject.abi.js:1046:12)
    at TupleCoder.encode (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/npm-ns.ethersproject.abi.js:1354:16)
    at AbiCoder.encode (chrome-extension://oeaicbdbafnmgeghifjjjibodncddfmk/js/npm-ns.ethersproject.abi.js:1443:15)</pre>

## Build info
- Version: 1.35.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-09T03:02:48.089Z
- VERSION: v1.29.12-726-gb0d463dd7

## Git (*):

b0d463dd7 (hotfix/1.35.2) on tag "v1.35.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Checked.
