### ISSUE TITLE
[Crash] Error: Unknown chain id.(ITO's plugin card was showing error in xDai)

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#3910]
I changed Metamask to xDai network, then ITO's plugin card  reports an error.
It suppose to show "Not available on xDAI Chain Network" and switch network button.
<img width="790" alt="Screen Shot 2021-08-09 at 5 33 43 PM" src="https://user-images.githubusercontent.com/85149605/128686690-a9b58255-d86b-4402-8e43-7035ccd47bbe.png">

> Unknown chain id.

Error stack:

<pre>Error: Unknown chain id.
    at useFungibleTokensDetailed (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/9098.js:29164:28)
    at PostInspector (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/chunk.7609.js:2907:170)
    at Ch (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/npm.react-dom.js:232:137)
    at si (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/npm.react-dom.js:259:255)
    at gk (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/npm.react-dom.js:356:346)
    at fk (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/npm.react-dom.js:343:22)
    at ek (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/npm.react-dom.js:342:369)
    at Vj (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/npm.react-dom.js:342:229)
    at Pj (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/npm.react-dom.js:331:476)
    at J (chrome-extension://bdddgebbfaiflnliaicpcgikhkaigikd/js/9098.js:19979:203)</pre>

## Build info
- Version: 1.35.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-09T03:02:48.089Z
- VERSION: v1.29.12-726-gb0d463dd7

## Git (*):

b0d463dd7 (hotfix/1.35.2) on tag "v1.35.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by guanbinrui** [comment]
@zhouhanseng The `<EthereumChainBoundary />` is not using.

**Comment by wenluomask** [comment]
Checked.
