### ISSUE TITLE
[Crash] SyntaxError: Cannot convert NaN to a BigInt

### ISSUE THREAD

**Issue by Cryptlesh** [DimensionDev/Maskbook#3972]
I was swapping currency on matic network, I wanted to swap 0.1 Matic for testing so I entered .1 instead of 0.1 (without preceding 0 digit), then Mask reports an error.

> Cannot convert NaN to a BigInt

I usually tend to write numbers without 0 when only decimal values need to enter and other dex doesn't give such exception. However entering 0.1 works well. So its not a big issue or blocking issue. May be some script validation issue here which doesn't handle this case.

Error stack:

<pre>SyntaxError: Cannot convert NaN to a BigInt
    at Function.value (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jsbi.js:6:7264)
    at toUniswapCurrencyAmount (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.9880.js:694:125)
    at useTrade_useTrade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6998.js:3439:68)
    at trader_useTradeComputed_useTradeComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6998.js:3835:22)
    at useTradeStateComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6998.js:3893:27)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6998.js:3974:131)
    at Ch (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:232:137)
    at si (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:259:255)
    at gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:356:346)
    at fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:22)</pre>

## Build info
- Version: 1.35.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-10T08:03:20.001Z
- VERSION: v1.29.12-735-g7cf5dd33b

## Git ():

7cf5dd33b (released) on tag "v1.35.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by guanbinrui** [comment]
Thanks for reporting it. We will fix this ASAP.
