### ISSUE TITLE
[Crash] Error: TODO

### ISSUE THREAD

**Issue by 382303784** [DimensionDev/Maskbook#4017]
I was *doing something...*, then Mask reports an error.

> TODO

Error stack:

<pre>Error: TODO
    at useCurrentTradeProvider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6998.js:6826:19)
    at TraderDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.6998.js:4249:85)
    at Ch (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:232:137)
    at gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:355:29)
    at fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:343:22)
    at ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:342:369)
    at Vj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:342:229)
    at Nj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:334:217)
    at hg (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:195:129)</pre>

## Build info
- Version: 1.35.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-10T08:03:20.001Z
- VERSION: v1.29.12-735-g7cf5dd33b

## Git ():

7cf5dd33b (released) on tag "v1.35.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by guanbinrui** [comment]
It will be fixed in [v1.36.2](https://github.com/DimensionDev/Maskbook/releases/tag/v1.36.2).
