### ISSUE TITLE
[Crash] SyntaxError: Cannot convert NaN to a BigInt

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#4032]
I was *doing something...*, then Mask reports an error.

> Cannot convert NaN to a BigInt

Error stack:

<pre>SyntaxError: Cannot convert NaN to a BigInt
    at Function.value (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.jsbi.js:6:7256)
    at toUniswapCurrencyAmount (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:5193:103)
    at useTrade_useTrade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4024:68)
    at useV2Trade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4034:92)
    at trader_useTradeComputed_useTradeComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4462:24)
    at useTradeStateComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4528:27)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4609:131)
    at Ch (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:171:137)
    at si (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:198:255)
    at gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:295:346)</pre>

## Build info
- Version: 1.36.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-16T03:24:23.431Z
- VERSION: v1.29.12-782-g67b3ccc71

## Git ():

67b3ccc71 (released) on tag "v1.36.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by AinuX** [comment]
dup of #3972
