### ISSUE TITLE
[Crash] TypeError: Cannot read property '137' of undefined

### ISSUE THREAD

**Issue by Jamalulinsan21** [DimensionDev/Maskbook#4048]
I was *doing something...*, then Mask reports an error.

> Cannot read property '137' of undefined

Error stack:

<pre>TypeError: Cannot read property '137' of undefined
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:3363:108
    at Object.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:187:120)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/8222.js:134:214)
    at useAllCurrencyCombinations (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:3359:36)
    at useAllCommonPairs (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:3438:37)
    at useV2BestTradeExactIn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:3467:59)
    at useV2Trade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4036:32)
    at trader_useTradeComputed_useTradeComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4462:24)
    at useTradeStateComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4528:27)
    at Trader (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.752.js:4609:131)</pre>

## Build info
- Version: 1.36.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-16T03:24:23.431Z
- VERSION: v1.29.12-782-g67b3ccc71

## Git ():

67b3ccc71 (released) on tag "v1.36.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by AinuX** [comment]
already fixed in 1.36.2
dup of #3980
