### ISSUE TITLE
[Crash] Error: Private key must be 32 bytes long

### ISSUE THREAD

**Issue by Jamalulinsan21** [DimensionDev/Maskbook#4079]
I was *doing something...*, then Mask reports an error.

> Private key must be 32 bytes long

Error stack:

<pre>Error: Private key must be 32 bytes long
    at Accounts.sign (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.web3-eth-accounts.js:793:15)
    at RedPacket (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.1950.js:1854:176)
    at Ch (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:171:137)
    at gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:294:29)
    at fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:282:22)
    at ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:281:369)
    at Vj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:281:229)
    at Pj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:270:476)
    at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6674.js:19025:203)
    at MessagePort.R (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6674.js:19026:123)</pre>

## Build info
- Version: 1.36.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-16T11:46:43.666Z
- VERSION: v1.29.12-788-g27e365af6

## Git ():

27e365af6 (released) on tag "v1.36.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by zhouhanseng** [comment]
@Jamalulinsan21 Could you please provide the twitter link?

**Comment by Jamalulinsan21** [comment]
https://twitter.com/Keithprayer/status/1430034074027003909?s=20

**Comment by zhouhanseng** [comment]
@Jamalulinsan21 

Could you please describe how to reproduce it, since I can't reproduce by whether send red packet directly or from the history list 🤔. Thank you.

**Comment by AinuX** [comment]
Found a way to reproduce this issue,  and it's a common issue in ITO and RedPacked.
1. Create a ITO or RedPack, but don't send 
2. Uninstall and reinstall plugin
3. Resend ITO or RedPack in past

Uninstallation will cause the data wipe out, so there will be a "Key" data miss when resend after reinstallation.
