### ISSUE TITLE
[Crash] TypeError: Cannot read property 'price' of undefined

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4119]
I was checking goodghosting plugin, then Mask reports an error.
You can check in my tweet: https://twitter.com/WEN6666661/status/1430812090176999428

> Cannot read property 'price' of undefined

Error stack:

<pre>TypeError: Cannot read property 'price' of undefined
    at getGameFinancialData (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/chunk.5700.js:650:144)
    at GameStatsView (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/chunk.5700.js:737:56)
    at Ch (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/npm.react-dom.js:171:137)
    at si (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/npm.react-dom.js:198:255)
    at gk (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/npm.react-dom.js:295:346)
    at fk (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/npm.react-dom.js:282:22)
    at ek (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/npm.react-dom.js:281:369)
    at Vj (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/npm.react-dom.js:281:229)
    at Pj (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/npm.react-dom.js:270:476)
    at J (chrome-extension://jakghbpaimhbeekmnllkccjdobjjhgbf/js/5660.js:19512:203)</pre>

## Build info
- Version: 1.36.3
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-08-26T08:21:44.529Z
- VERSION: v1.29.12-810-g4457f8e7b

## Git (*):

4457f8e7b (hotfix/1.36.3) on tag "v1.36.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by AinuX** [comment]
@OsamaElHariri

**Comment by OsamaElHariri** [comment]
Checked this out. It looks like a fix has already been pushed in this PR: https://github.com/DimensionDev/Maskbook/pull/4159

**Comment by wenluomask** [comment]
Yes it fixed by #4159.
