### ISSUE TITLE
[Crash] Error:  is not a valid address.(swap in Arbitrum Network)

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4185]
I was trying to swap in Arbitrum Network, then Mask reports an error.

>  is not a valid address.

Error stack:

<pre>Error:  is not a valid address.
    at validateAndParseAddress (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.uniswap.sdk-core.js:545:11)
    at new Token (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.uniswap.sdk-core.js:562:21)
    at toUniswapToken (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5087.js:5278:12)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5087.js:3449:54
    at Array.map (<anonymous>)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5087.js:3449:11
    at Object.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:187:120)
    at exports.useMemo (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6384.js:141:214)
    at useAllCurrencyCombinations (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5087.js:3436:36)
    at useAllCommonPairs (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5087.js:3515:37)</pre>

## Build info
- Version: 1.36.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- firefoxVariant: false
- resolution: desktop
- BUILD_DATE: 2021-09-02T02:50:16.586Z
- VERSION: v1.29.12-924-gb596bf052

## Git (*):

b596bf052 (develop) on tag "v1.36.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
It still failed to swap ARETH->Link in latest version of develop.

https://user-images.githubusercontent.com/85149605/132164267-8d327053-a523-43a4-a2bd-793e3d2bd21f.mov

**Comment by Tedko** [comment]
anyone fix this?

**Comment by wenluomask** [comment]
Fixed.
