### ISSUE TITLE
[Crash] Error occurs when swap by using WalletConnect wallet

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4727]
I used imtoken wallet(Wallet Connect) to swap, then Mask reports an error after a while.
It may caused by no tx found.

<img width="1364" alt="Screen Shot 2021-11-01 at 2 54 04 PM" src="https://user-images.githubusercontent.com/85149605/139633742-fd3f9100-ae00-4319-8376-312a9ea0561b.png">

<img width="1379" alt="Screen Shot 2021-10-31 at 3 50 55 PM" src="https://user-images.githubusercontent.com/85149605/139573573-2f0116e9-7e4a-49bf-a0bf-dd5aa4d3034e.png">

> Path parameter tx cannot be of type undefined. Allowed types are: boolean, string, number.

Error stack:

<pre>TypeError: Path parameter tx cannot be of type undefined. Allowed types are: boolean, string, number.
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:36885:19
    at String.replace (<anonymous>)
    at path (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:36876:33)
    at urlcatImpl (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:36829:14)
    at urlcat (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:36819:16)
    at resolveTransactionLinkOnExplorer (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:35274:33)
    at TransactionDialogUI (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.7926.js:4444:143)
    at Ah (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:171:249)
    at Mi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:221:256)
    at sk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:301:152)</pre>

**Comment by wenluomask** [comment]
Swap successfully but error will still come out.
<img width="1867" alt="截屏2021-11-15 下午3 30 06" src="https://user-images.githubusercontent.com/85149605/141739952-f8868252-56c3-4dc9-9d76-255904b74802.png">

**Comment by Tedko** [comment]
is this fixed? @wenluomask @guanbinrui

**Comment by wenluomask** [comment]
Still exists.

**Comment by wenluomask** [comment]
Issue in Jira: https://mask.atlassian.net/browse/MASK-650

**Comment by wenluomask** [comment]
Fixed.
