### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4733]
I was claiming token in BSC, then change to Polygon tab, then Mask reports an error.
It occured in branchj hancheng/hide-unused-entry

<img width="664" alt="Screen Shot 2021-11-01 at 4 48 20 PM" src="https://user-images.githubusercontent.com/85149605/139646028-df1bce13-b269-4996-b436-8e979648b294.png">

> Cannot read properties of undefined (reading 'filter')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'filter')
    at chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/chunk.1790.js:1831:47
    at pj (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:248:366)
    at dk (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:295:100)
    at ak (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:281:185)
    at fg (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:134:105)
    at tk (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:292:345)
    at lk (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:290:64)
    at ck (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:279:210)
    at J (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/2957.js:16900:203)
    at MessagePort.R (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/2957.js:16901:128)</pre>

## Build info
- Version: 2.0.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2021-11-01T04:30:46.831Z
- VERSION: v1.29.12-1249-g34e10f098

## Git (*):

34e10f098 (hancheng/hide-unused-entry) on tag "v2.0.0-beta"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Mask also was showing Polygon is invalid network.
<img width="1644" alt="Screen Shot 2021-11-01 at 4 44 31 PM" src="https://user-images.githubusercontent.com/85149605/139646230-ae8bea62-1727-42a3-8f71-1e1df6e9ea74.png">

**Comment by wenluomask** [comment]
https://user-images.githubusercontent.com/85149605/139646750-6b0e5290-77cc-416e-8a07-f977fde0c925.mov

**Comment by wenluomask** [comment]
<img width="578" alt="Screen Shot 2021-11-01 at 5 18 26 PM" src="https://user-images.githubusercontent.com/85149605/139649882-2ba51287-945e-4801-bd39-ccf8ef281f23.png">

**Comment by wenluomask** [comment]
Checked.
