### ISSUE TITLE
[Crash] TypeError: Invalid Username

### ISSUE THREAD

**Issue by vietanh2131** [DimensionDev/Maskbook#4793]
I was ,just browsing, then Mask reports an error.

> Invalid Username

Error stack:

<pre>TypeError: Invalid Username
    at getPostUrlAtFacebook (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8939.js:1239:49)
    at Object.getPostURL [as getURLFromPostIdentifier] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8939.js:21:200)
    at Object.getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8446.js:5980:119)
    at DecryptPost.ref (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8446.js:5425:44)
    at pj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:248:366)
    at dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:295:100)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:277:86)
    at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:16900:203)
    at MessagePort.R (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:16901:128)</pre>

## Build info
- Version: 2.0.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2021-11-02T11:15:35.966Z
- VERSION: v1.29.12-1296-gf03237e1f

## Git ():

f03237e1f (released) on tag "v2.0.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by zhouhanseng** [comment]
@vietanh2131 Sorry for the delay, thanks for reporting.

This is a strategy bug, would you mind provide your fb id to help me to debug?

**Comment by vietanh2131** [comment]
Sure! https://www.facebook.com/vietanh.lekim.792/

------ Original Message ------
From: "Hancheng Zhou" ***@***.***>
To: "DimensionDev/Maskbook" ***@***.***>
Cc: "vietanh2131" ***@***.***>; "Mention" 
***@***.***>
Sent: 11/23/2021 3:00:15 PM
Subject: Re: [DimensionDev/Maskbook] [Crash] TypeError: Invalid Username 
(Issue #4793)

>
***@***.*** <https://github.com/vietanh2131> Sorry for the delay,
