### ISSUE TITLE
[Crash] occurred when open new swap's confirmation page

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4880]
I was going to confirmation page to confirm the swap, then Mask reports an error.

> Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error stack:

<pre>Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at hh (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:157:60)
    at I (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:167:372)
    at Si (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:213:377)
    at Fk (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:298:487)
    at Ek (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:285:22)
    at Dk (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:284:376)
    at rk (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:284:236)
    at wk (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:275:418)
    at nk (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:277:300)
    at dg (chrome-extension://demoafjpoidcpjdinfddgheppmkbibel/js/npm.react-dom.js:133:105)</pre>

## Build info
- Version: 2.0.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2021-11-22T07:52:11.278Z
- VERSION: v1.29.12-1384-g8e734e543

## Git (*):

8e734e543 (feat/new-swap) on tag "v2.0.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by AinuX** [comment]
Maybe it's same issue of #4876

**Comment by wenluomask** [comment]
Maybe not.
