### ISSUE TITLE
[Crash] TypeError: Invalid Username

### ISSUE THREAD

**Issue by haydave** [DimensionDev/Maskbook#4884]
I was scrolling in the one of facebook groups, then Mask reports an error.
error_boundary_crash_title above post.

> Invalid Username

Error stack:

<pre>TypeError: Invalid Username
    at getPostUrlAtFacebook (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8939.js:1239:49)
    at Object.getPostURL [as getURLFromPostIdentifier] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8939.js:21:200)
    at Object.getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8446.js:5980:119)
    at DecryptPost.ref (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8446.js:5425:44)
    at pj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:248:366)
    at dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:295:100)
    at ck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:277:86)
    at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:16900:203)
    at MessagePort.R (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2430.js:16901:128)</pre>

## Build info
- Version: 2.0.2
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2021-11-02T11:15:35.966Z
- VERSION: v1.29.12-1296-gf03237e1f

## Git ():

f03237e1f (released) on tag "v2.0.2"
git@github.com:DimensionDev/Maskbook.git

**Comment by zhouhanseng** [comment]
@haydave thanks for your reporting!

This is a strategy bug, it took me a while but still unable to recur. Would you mind provide your fb id to help me to debug it?

**Comment by haydave** [comment]
Yep. My ID is imdvd <https://www.facebook.com/imdvd>. Post, where the issue
is visible, is available here
<https://www.facebook.com/permalink.php?story_fbid=2077533122422690&id=437617976414221>
.
