### ISSUE TITLE
[Crash] Error: Path parameter domain cannot be an empty string.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#4941]
I was sending token by using ens, then Mask reports an error. Tested in pr feat/ens-support.

> Path parameter domain cannot be an empty string.

Error stack:

<pre>Error: Path parameter domain cannot be an empty string.
    at chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/6321.js:33394:19
    at String.replace (<anonymous>)
    at path (chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/6321.js:33381:33)
    at urlcatImpl (chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/6321.js:33334:14)
    at urlcat (chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/6321.js:33329:16)
    at Object.resolveEnsDomains (chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/6321.js:32268:57)
    at chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/chunk.2526.js:1463:162
    at Mh (chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/npm.react-dom.js:172:250)
    at Yi (chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/npm.react-dom.js:218:256)
    at Xi (chrome-extension://acfifcjpfaibfjdkmmieaaimolcbmgna/js/npm.react-dom.js:216:174)</pre>

**Comment by wenluomask** [comment]
Please check the video to see how to reproduce.

https://user-images.githubusercontent.com/85149605/144286293-f01b285c-e278-459d-b0d8-33615d4de7f5.mov
