### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#5142]
I was trying to open token list from lucky drop when no wallet is connected(You can enter here from compose), then Mask reports an error.

> Cannot read properties of undefined (reading '1')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading '1')
    at useAssetsFromChain (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/666.js:34799:82)
    at useAssetsByTokenList (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/666.js:34719:238)
    at FixedTokenList (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/chunk.9130.js:3583:117)
    at Mh (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/npm.react-dom.js:172:250)
    at Fk (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/npm.react-dom.js:295:386)
    at Ek (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/npm.react-dom.js:285:22)
    at Dk (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/npm.react-dom.js:284:376)
    at rk (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/npm.react-dom.js:284:236)
    at wk (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/npm.react-dom.js:275:418)
    at nk (chrome-extension://ebnbhnclkapfglfbpiicofbcnmlhlhgf/js/npm.react-dom.js:277:300)</pre>

## Build info
- Version: 2.2.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2021-12-10T06:53:41.261Z
- VERSION: v1.29.12-1508-g87aa767e6

## Git (*):

87aa767e6 (develop) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Already fixed.
