### ISSUE TITLE
[Crash] Error: Unreachable case:Fungible

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#5144]
I clicked token's send button from Dashboard's Asset page, then Mask reports an error. (Please check in develop.)
<img width="993" alt="Screen Shot 2021-12-10 at 4 34 52 PM" src="https://user-images.githubusercontent.com/85149605/145542914-f7ef0e48-a7be-451c-8f7e-c354bae4d5f5.png">

> Unreachable case:Fungible

Error stack:

<pre>Error: Unreachable case:Fungible
    at unreachable (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/666.js:44604:11)
    at useFungibleTokenBalance (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/666.js:36675:85)
    at chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/chunk.545.js:1660:111
    at Mh (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/npm.react-dom.js:172:250)
    at Yi (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/npm.react-dom.js:218:256)
    at Xi (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/npm.react-dom.js:216:174)
    at Vi (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/npm.react-dom.js:215:176)
    at Fk (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/npm.react-dom.js:302:16)
    at Ek (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/npm.react-dom.js:285:22)
    at Dk (chrome-extension://okjhhcojocoddlbhmohgcmjnknbecmjf/js/npm.react-dom.js:284:376)</pre>

**Comment by wenluomask** [comment]
Fixed in 2.2.2 by binrui.
