### ISSUE TITLE
[Crash] Error: Component must be wrapped with <Container.Provider>

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#5155]
I was *doing something...*, then Mask reports an error.

> Component must be wrapped with <Container.Provider>

Error stack:

<pre>Error: Component must be wrapped with <Container.Provider>
    at Object.useContainer (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7398.js:42000:13)
    at useTradeContext (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.4300.js:783:138)
    at SwapBox (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.4300.js:386:68)
    at Mh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:172:250)
    at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:295:386)
    at Ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:22)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:376)
    at rk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:236)
    at wk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:275:418)
    at nk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:277:300)</pre>

## Build info
- Version: 2.2.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2021-12-08T13:04:58.864Z
- VERSION: v1.29.12-1484-g803c7d1d5

## Git ():

803c7d1d5 (released) on tag "v2.2.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by Tedko** [comment]
Tried to click swap here 
<img width="1302" alt="Screen Shot 2021-12-11 at 02 44 02" src="https://user-images.githubusercontent.com/6687437/145625488-7f85194d-ae33-4db2-9393-f329debdab73.png">


P0 issue

**Comment by AinuX** [comment]
Checked
