### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading '137')

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#5163]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading '137')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading '137')
    at useAssetsFromChain (../web3-shared/evm/hooks/useAssetsFromChain.ts:31:82)
    at useAssetsByTokenList (../web3-shared/evm/hooks/useAssetsByTokenList.ts:38:229)
    at FixedTokenList (./src/extension/options-page/DashboardComponents/FixedTokenList.tsx:81:158)
    at renderWithHooks (npm:react-dom/cjs/react-dom.development.js:16182:18)
    at mountIndeterminateComponent (npm:react-dom/cjs/react-dom.development.js:20758:13)
    at beginWork (npm:react-dom/cjs/react-dom.development.js:22267:16)
    at beginWork$1 (npm:react-dom/cjs/react-dom.development.js:27049:14)
    at performUnitOfWork (npm:react-dom/cjs/react-dom.development.js:26238:12)
    at workLoopSync (npm:react-dom/cjs/react-dom.development.js:26148:5)
    at renderRootSync (npm:react-dom/cjs/react-dom.development.js:26116:7)</pre>

## Build info
- Version: 2.2.0
- NODE_ENV: development
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2021-12-11T17:47:23.372Z
- VERSION: v1.29.12-1506-g335fc02bd-dirty

## Git (*):

335fc02bd (fix/watch-speed-up-tx) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by AinuX** [comment]
Checked
