### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'suggestedMaxFeePerGas')

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#5197]
I was try to send token in popup, when I choose token, then Mask reports an error.

> Cannot read properties of undefined (reading 'suggestedMaxFeePerGas')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'suggestedMaxFeePerGas')
    at chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/js/chunk.2903.js:528:95
    at chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/js/npm.react-use.js:955:20
    at Dj (chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/js/npm.react-dom.js:245:332)
    at rk (chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/js/npm.react-dom.js:291:100)
    at chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/js/npm.react-dom.js:287:387
    at J (chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/js/4926.js:19613:203)
    at R (chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/js/4926.js:19614:128)
    at queue.<computed> (chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/polyfill/ecmascript.js:4475:7)
    at run (chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/polyfill/ecmascript.js:4451:5)
    at MessagePort.listener (chrome-extension://mnhingnolenldfbjnlmgbpapmenbkccc/polyfill/ecmascript.js:4462:3)</pre>

## Build info
- Version: 2.2.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2021-12-15T09:36:08.031Z
- VERSION: v1.29.12-1548-g71f53c08a

## Git (*):

71f53c08a (feat/replace-token-list) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
found in pr feat/replace-token-list

**Comment by wenluomask** [comment]
Fixed in https://github.com/DimensionDev/Maskbook/pull/5143
