### ISSUE TITLE
[Crash] Error: Invariant failed

### ISSUE THREAD

**Issue by orange187** [DimensionDev/Maskbook#5316]
I was *doing something...*, then Mask reports an error.

> Invariant failed

Error stack:

<pre>Error: Invariant failed
    at invariant (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/8583.js:38412:15)
    at new t (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/chunk.npm-ns.uniswap.v3-sdk.js:21:31192)
    at Function.t.createUncheckedTrade (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/chunk.npm-ns.uniswap.v3-sdk.js:21:34592)
    at chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/chunk.4001.js:5130:31
    at useV3BestTradeExactIn (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/chunk.4001.js:5139:7)
    at useV3Trade (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/chunk.4001.js:5276:32)
    at useAllTradeComputed (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/chunk.4001.js:6123:24)
    at useAllProviderTradeContext (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/chunk.4001.js:6284:30)
    at Provider (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/8583.js:44533:17)
    at Mh (chrome-extension://pagjgaggjdgdkbppldaokegfbghkpeei/js/npm.react-dom.js:172:137)</pre>

## Build info
- Version: 2.3.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2021-12-20T12:09:49.300Z
- VERSION: v1.29.12-1605-g65399e174

## Git (*):

65399e174 (fix/collectibles-issues) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Probably occurred when doing swap in collectible plugin.

**Comment by developerfred** [comment]
is using the maskbook address and not an evm like 0x address, so this error is happening. TraderPlugin expects an address 0x...

**Comment by wenluomask** [comment]
Can not reproduce.
