### ISSUE TITLE
[Crash] Error: Can't autodetect provider for "MetaMask"

### ISSUE THREAD

**Issue by vaimeo** [DimensionDev/Maskbook#5372]
I was *doing something...*, then Mask reports an error.

> Can't autodetect provider for "MetaMask"

Error stack:

<pre>Error: Can't autodetect provider for "MetaMask"
    at RequestManager.setProvider (npm:web3-core-requestmanager/lib/index.js:75:19)
    at new RequestManager (npm:web3-core-requestmanager/lib/index.js:39:10)
    at Object.packageInit (npm:web3-core/lib/index.js:45:31)
    at new Web3 (npm:web3/lib/index.js:39:10)
    at SetOfferForm (./src/plugins/Traderxyz/SNSAdaptor/trader/SetOfferForm.tsx:77:18)
    at renderWithHooks (npm:react-dom/cjs/react-dom.development.js:16186:18)
    at mountIndeterminateComponent (npm:react-dom/cjs/react-dom.development.js:20775:13)
    at beginWork (npm:react-dom/cjs/react-dom.development.js:22284:16)
    at beginWork$1 (npm:react-dom/cjs/react-dom.development.js:27066:14)
    at performUnitOfWork (npm:react-dom/cjs/react-dom.development.js:26255:12)</pre>

## Build info
- Version: 2.3.0
- NODE_ENV: development
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-01-03T07:16:16.309Z
- VERSION: v1.29.12-1640-gee47acd9d-dirty

## Git (*):

ee47acd9d (develop) on tag "v2.1.0"
https://github.com/DimensionDev/Maskbook.git

**Comment by guanbinrui** [comment]
It's not a production plugin.
