### ISSUE TITLE
[Crash] Error: Invariant failed

### ISSUE THREAD

**Issue by caoxmm** [DimensionDev/Maskbook#5381]
when i try to swap ETH -> MASK use Mask Network (2.3.1) plugin(in chrome 96.0.4664.110) from twitter.

1. search $MASK in twitter
![image](https://user-images.githubusercontent.com/30405262/148090795-514172a9-0e4c-4a2e-b077-c4bc2f01da12.png)
2. click '兑换' which means swap form the area below the search input.
![image](https://user-images.githubusercontent.com/30405262/148090975-052ee581-aa8c-4a86-8c9b-4e8a4de063e4.png)

3. then this area shows this error.
![image](https://user-images.githubusercontent.com/30405262/148091023-2b50a226-4155-49a0-a13c-e4d3e946711c.png)

> Invariant failed

Error stack:

<pre>Error: Invariant failed
    at invariant (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5757.js:38935:15)
    at Token.BaseCurrency (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.uniswap.sdk-core.js:510:141)
    at new Token (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm-ns.uniswap.sdk-core.js:559:27)
    at toUniswapToken (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8198.js:3870:12)
    at toUniswapCurrency (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8198.js:3867:90)
    at useTrade_useTrade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8198.js:5245:65)
    at useV2Trade (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8198.js:5256:92)
    at useAllTradeComputed (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8198.js:6090:24)
    at useAllProviderTradeContext (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.8198.js:6283:30)
    at Provider (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5757.js:45084:17)</pre>

## Build info
- Version: 2.3.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2021-12-22T17:18:59.065Z
- VERSION: v1.29.12-1575-ge5ce52bbf

## Git ():

e5ce52bbf (released) on tag "v2.3.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by caoxmm** [comment]
it weird, its worked in my other compute.
