### ISSUE TITLE
[Crash] Error: [BigNumber Error] Argument not an integer: NaN

### ISSUE THREAD

**Issue by orange187** [DimensionDev/Maskbook#5383]
I was try to swap from clicking "get more DAI" button, then Mask reports an error.

> [BigNumber Error] Argument not an integer: NaN

Error stack:

<pre>Error: [BigNumber Error] Argument not an integer: NaN
    at intCheck (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/npm.bignumber.js.js:8474:13)
    at BigNumber.P.shiftedBy (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/npm.bignumber.js.js:7999:7)
    at rightShift (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/229.js:778:73)
    at chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/chunk.315.js:2722:54
    at Object.qi [as useMemo] (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/npm.react-dom.js:183:119)
    at exports.useMemo (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/2000.js:4950:297)
    at MakeOfferDialog (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/chunk.315.js:2719:48)
    at Mh (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/npm.react-dom.js:172:137)
    at Zi (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/npm.react-dom.js:218:256)
    at Gk (chrome-extension://ogllhbgmamcggllocglncccbknonfcna/js/npm.react-dom.js:297:202)</pre>

## Build info
- Version: 2.3.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-01-04T13:18:13.402Z
- VERSION: v1.29.12-1679-g9106240c0(lelenei/mask-518)

## Git (*):

9106240c0 (lelenei/mask-518) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/3cbd9ec77b3add98bb54373078bf209501c9c741/packages/mask/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx#L140-L143

**Comment by septs** [comment]
CC @BillySh1 @zhouhanseng @guanbinrui

**Comment by lelenei** [comment]
mask-518
