### ISSUE TITLE
[Crash] Error: [BigNumber Error] Argument not an integer: NaN

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#5447]
I was trying to create a NFT lucky drop,  then Mask reports an error after send the request to popup wallet.
Here is the pr I used: https://github.com/DimensionDev/Maskbook/pull/5437

<img width="1231" alt="Screen Shot 2022-01-14 at 1 24 20 PM" src="https://user-images.githubusercontent.com/85149605/149456359-d56f9c4b-5d73-40ad-8950-446f8985f0e6.png">

> [BigNumber Error] Argument not an integer: NaN

Error stack:

<pre>Error: [BigNumber Error] Argument not an integer: NaN
    at intCheck (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.bignumber.js.js:8474:13)
    at BigNumber.P.shiftedBy (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.bignumber.js.js:7999:7)
    at leftShift (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/9485.js:30631:73)
    at chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/chunk.4600.js:328:106
    at Mh (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.react-dom.js:172:137)
    at Zi (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.react-dom.js:218:256)
    at Yi (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.react-dom.js:216:174)
    at Gk (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.react-dom.js:302:45)
    at Fk (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.react-dom.js:285:22)
    at Ek (chrome-extension://oanbmfieemcilbmcopefmpfibnjnnhii/js/npm.react-dom.js:284:410)</pre>

## Build info
- Version: 2.3.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-01-14T03:49:44.929Z
- VERSION: v1.29.12-1739-g8ef1ff483

## Git (*):

8ef1ff483 (hancheng/optimise-ito-redpacket) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Fixed in #5437
