### ISSUE TITLE
[Crash] Error: Extension context invalidated.

### ISSUE THREAD

**Issue by Zen177muhammad** [DimensionDev/Maskbook#5508]
I was *doing something...*, then Mask reports an error.

> Extension context invalidated.

Error stack:

<pre>Error: Extension context invalidated.
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.9528.js:432:114
    at Mh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:172:137)
    at Zi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:218:256)
    at Yi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:216:174)
    at Wi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:215:176)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:302:16)
    at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:22)
    at Ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:410)
    at sk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:270)
    at xk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:275:418)</pre>

**Comment by Jack-Works** [comment]
Hi, this is because the Mask background has been killed by the browser. It's usually happened in the development of Mask but does not usually happen in the production. How do you trigger this problem?

**Comment by Zen177muhammad** [comment]
I don't know sir.
I'm just following the instructions
Is there any solution for my problem sirr.??

Pada tanggal Sab, 22 Jan 2022 11.53, Jack Works ***@***.***>
menulis:

**Comment by Jack-Works** [comment]
Are you trying to develop Mask Network or just a user? If the latter, refresh the web page can resolve this problem.

**Comment by Zen177muhammad** [comment]
I don't know.

Pada tanggal Sab, 22 Jan 2022 23.38, Jack Works ***@***.***>
menulis:

**Comment by Zen177muhammad** [comment]
Can i get a reward sir🙂

Pada tanggal Jum, 25 Mar 2022 06.48, stale[bot] ***@***.***>
menulis:

**Comment by Jack-Works** [comment]
I'm sorry but this bug report looks like an occidental bug and we can do nothing to fix it
