### ISSUE TITLE
[Crash] ReferenceError: process is not defined

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#5525]
I just download and install Mask extension(2.4.0 version), then Mask reports an error.

> process is not defined

Error stack:

<pre>ReferenceError: process is not defined    at Object.25466 (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/chunk.4121.js:1449:20)
    at __webpack_require__ (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/background.js:2375:42)
    at Module.21524 (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/chunk.5334.js:11485:26)
    at __webpack_require__ (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/background.js:2375:42)
    at Object.78368 (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/chunk.6835.js:1039:82)
    at __webpack_require__ (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/background.js:2375:42)
    at Module.78683 (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/chunk.6835.js:103:21)
    at Function.__webpack_require__ (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/background.js:2375:42)
    at async getLocalImplementation (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/295.js:26895:20)
    аt AsyncCall (rpc) 
    at revalidate (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/295.js:28897:16)
    at getCurrentValue (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/295.js:28882:45)
    at chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/527.js:1842:142
    at Object.ei [as useState] (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/npm.react-dom.js:179:270)
    at Object.exports.useState (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/295.js:15340:483)
    at exports.useSubscription (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/527.js:1842:79)
    at useData (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/295.js:28894:81)
    at usePersonaContext (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/chunk.213.js:1853:54)
    at Provider (chrome-extension://ccllphcbjncagihbfdcpccnfoeghnjcj/js/295.js:39044:17)</pre>

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/151106851-557d613a-b410-4f86-a963-a7527f9ac1d3.png)

**Comment by Jack-Works** [comment]
@NikoManiac

**Comment by wenluomask** [comment]
Fixed.
