### ISSUE TITLE
[Crash] Error: invalid address (argument="address", value=null, code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value=null, code=INVALID_ARGUMENT, version=abi/5.0.7)

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#5540]
I was viewing Goodghosting plugin, then Mask reports an error.
https://twitter.com/WenLuo04001516/status/1423313410410782720

> invalid address (argument="address", value=null, code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value=null, code=INVALID_ARGUMENT, version=abi/5.0.7)

Error stack:

<pre>Error: invalid address (argument="address", value=null, code=INVALID_ARGUMENT, version=address/5.4.0) (argument=null, value=null, code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/9344.js:1511:23)
    at Logger.throwError (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/9344.js:1520:20)
    at Logger.throwArgumentError (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/9344.js:1523:21)
    at AddressCoder._throwError (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/npm-ns.ethersproject.abi.js:851:31)
    at AddressCoder.encode (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/npm-ns.ethersproject.abi.js:977:18)
    at chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/npm-ns.ethersproject.abi.js:1060:19
    at Array.forEach (<anonymous>)
    at pack (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/npm-ns.ethersproject.abi.js:1046:12)
    at TupleCoder.encode (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/npm-ns.ethersproject.abi.js:1354:16)
    at AbiCoder.encode (chrome-extension://ipcjpncgaallafjnebaegbkgclcbllfk/js/npm-ns.ethersproject.abi.js:1443:15)</pre>

## Build info
- Version: 2.3.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-01-27T06:17:53.912Z
- VERSION: v1.29.12-1805-ge26ea5b94

## Git (*):

e26ea5b94 (develop) on tag "v2.1.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
@guanbinrui
