### ISSUE TITLE
[Crash] Error: [BigNumber Error] Argument not an integer: NaN

### ISSUE THREAD

**Issue by jaxo4life** [DimensionDev/Maskbook#5545]
I was *doing something...*, then Mask reports an error.

> [BigNumber Error] Argument not an integer: NaN

Error stack:

<pre>Error: [BigNumber Error] Argument not an integer: NaN
    at intCheck (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.bignumber.js.js:5572:13)
    at BigNumber.P.shiftedBy (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.bignumber.js.js:5097:7)
    at leftShift (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7643.js:780:73)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.1260.js:310:106
    at Mh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:172:137)
    at Zi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:218:256)
    at Yi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:216:174)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:302:45)
    at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:22)
    at Ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:410)</pre>

## Build info
- Version: 2.3.3
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-01-12T06:00:24.932Z
- VERSION: v1.29.12-1609-g09d2f504c

## Git ():

09d2f504c (released) on tag "v2.3.3"
git@github.com:DimensionDev/Maskbook.git

**Comment by guanbinrui** [comment]
@nuanyang233 

![image](https://user-images.githubusercontent.com/52657989/151668063-3e61bc34-bada-49f4-b2af-4aed38e8b20f.png)

**Comment by jaxo4life** [comment]
thx mate!

**Comment by Tedko** [comment]
@guanbinrui fixed?
