### ISSUE TITLE
[Crash] Error: Private key must be 32 bytes long

### ISSUE THREAD

**Issue by 1572817043** [DimensionDev/Maskbook#5600]
I was *doing something...*, then Mask reports an error.

> Private key must be 32 bytes long

Error stack:

<pre>Error: Private key must be 32 bytes long
    at Accounts.sign (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.web3-eth-accounts.js:365:15)
    at RedPacket (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.3898.js:5869:176)
    at Mh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:172:137)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:295:386)
    at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:22)
    at Ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:410)
    at sk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:270)
    at xk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:275:418)
    at ok (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:277:300)
    at dg (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:133:105)</pre>

## Build info
- Version: 2.4.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-01-31T05:09:13.691Z
- VERSION: v1.29.12-1857-g1f361be34

## Git ():

1f361be34 (released) on tag "v2.4.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by LonelyGypsie** [comment]
How to resolve this please

**Comment by hanszhoou** [comment]
@LonelyGypsie Could you please provide the twitter link cause this bug?
