### ISSUE TITLE
[Crash] Error: Minified React error #31

### ISSUE THREAD

**Issue by LindaMask** [DimensionDev/Maskbook#5672]
I was *doing something...*, then Mask reports an error.

> Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error stack:

<pre>Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ih (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:157:60)
    at w (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:161:186)
    at m (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:163:331)
    at H (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:167:334)
    at Ti (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:213:368)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:298:487)
    at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:22)
    at Ek (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:410)
    at sk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:284:270)
    at xk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:275:418)</pre>

## Build info
- Version: 2.4.3
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-02-08T03:56:00.909Z
- VERSION: v1.29.12-1863-gfef351db9

## Git ():

fef351db9 (released) on tag "v2.4.3"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
> Objects are not valid as a React child (found: object with keys {s, e, c}). If you meant to render a collection of children, use an array instead.

🤔.... strange error

**Comment by Jack-Works** [comment]
@LindaMask hi, can you tell me where is this error occurs?

**Comment by LindaMask** [comment]
@Jack-Works twitter, using mask plugin. I think I cleaned on the pfp and this appeared

**Comment by Jack-Works** [comment]
what is pfp?
