### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by layinka** [DimensionDev/Maskbook#5890]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'call')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'call')
    at Object.options.factory (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/dashboard.js:840:31)
    at __webpack_require__ (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/dashboard.js:98:33)
    at fn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/dashboard.js:507:21)
    at eval (../dashboard/src/pages/SignIn/index.tsx:7:79)
    at Module.../dashboard/src/pages/SignIn/index.tsx (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.dashboard_src_pages_SignIn_index_tsx.js:218:1)
    at Module.options.factory (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/dashboard.js:840:31)
    at __webpack_require__ (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/dashboard.js:98:33)
    at Function.fn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/dashboard.js:507:21)</pre>

**Comment by Jack-Works** [comment]
it looks like you're using a develop version 👀
