### ISSUE TITLE
[Crash] UnknownError: Internal error retrieving bucket data directory.

### ISSUE THREAD

**Issue by 00fff0** [DimensionDev/Maskbook#5904]
I was *doing something...*, then Mask reports an error.

> Internal error retrieving bucket data directory.

Error stack:

<pre>DOMException: Internal error retrieving bucket data directory.
    at RecoverError (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1062:20)
    at onResponse (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1583:17)
    at handleSingleMessage (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1688:16)
    at rawMessageReceiver (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1602:40)</pre>

**Comment by Jack-Works** [comment]
Hello, I searched on the internet, it seems like your Chrome data is broken...

https://jasonsavard.com/forum/discussion/7316/internal-error-retrieving-bucket-data-directory

I guess there is nothing much we can do for you, sorry!
