### ISSUE TITLE
[Crash] TypeError: Path parameter address cannot be of type undefined. Allowed types are: boolean, string, number.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6109]
I changed MetaMask's current wallet in Tips add wallet page, then Mask reports an error.
It only happened in the first time we connect MetaMask and change wallet.

Uploading 屏幕录制2022-04-20 上午1.18.49.mov…

> Path parameter address cannot be of type undefined. Allowed types are: boolean, string, number.

Error stack:

<pre>TypeError: Path parameter address cannot be of type undefined. Allowed types are: boolean, string, number.
    at chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/4191.js:39633:19
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at path (chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/4191.js:39624:33)
    at urlcatImpl (chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/4191.js:39577:14)
    at urlcat (chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/4191.js:39567:16)
    at Object.resolveAddressLinkOnExplorer [as resolveAddressLink] (chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/893.js:2035:57)
    at CurrentWalletBox (chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/chunk.2767.js:487:66)
    at Nh (chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/npm.react-dom.js:172:137)
    at cj (chrome-extension://kmcloeknmmjdbnieimbnbfokbnnochbl/js/npm.react-dom.js:220:217)</pre>

## Build info
- Version: 2.6.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-04-19T13:55:46.775Z
- VERSION: v1.29.12-2373-gf943d9d50

## Git (*):

f943d9d50 (feat/tips-enterance) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Fixed in https://github.com/DimensionDev/Maskbook/pull/6012
