### ISSUE TITLE
[Crash] TypeError: useSharedI18N is not a function

### ISSUE THREAD

**Issue by vaimeo** [DimensionDev/Maskbook#6132]
I was *opening the token list on swap click*, then Mask reports an error.

> (0 , _masknet_shared__WEBPACK_IMPORTED_MODULE_3__.useSharedI18N) is not a function

<img width="753" alt="image" src="https://user-images.githubusercontent.com/3579069/164816128-cea846ad-ffe6-4aad-8bb6-65f995c553dc.png">

Error stack:

<pre>TypeError: (0 , _masknet_shared__WEBPACK_IMPORTED_MODULE_3__.useSharedI18N) is not a function
  at SelectTokenDialog (../shared/src/contexts/evm/TokenPicker/SelectTokenDialog.tsx:63:77)
  at renderWithHooks (npm:react-dom/cjs/react-dom.development.js:16141:18)
  at mountIndeterminateComponent (npm:react-dom/cjs/react-dom.development.js:20833:13)
  at beginWork (npm:react-dom/cjs/react-dom.development.js:22337:16)
  at beginWork$1 (npm:react-dom/cjs/react-dom.development.js:27214:14)
  at performUnitOfWork (npm:react-dom/cjs/react-dom.development.js:26387:12)
  at workLoopSync (npm:react-dom/cjs/react-dom.development.js:26298:5)
  at renderRootSync (npm:react-dom/cjs/react-dom.development.js:26266:7)
  at recoverFromConcurrentError (npm:react-dom/cjs/react-dom.development.js:25684:20)
  at performSyncWorkOnRoot (npm:react-dom/cjs/react-dom.development.js:25930:20)</pre>

## Build info
- Version: 2.6.0
- NODE_ENV: development
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-04-22T22:57:42.640Z
- VERSION: v1.29.12-2299-g41f66330d-dirty

## Git (*):

41f66330d (develop) on tag "v2.5.0"
git@github.com:vaimeo/Maskbook.git

**Comment by developerfred** [comment]
@vaimeo Did you try to build with the latest version of the development environment?

**Comment by vaimeo** [comment]
No I didn't tried it yet, I tried pnpm start command.

**Comment by vaimeo** [comment]
After build it has the same problem as seen below.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/3579069/164890910-2ae6e317-3b9b-4311-87b4-fbd83ab15a32.png">

**Comment by Jack-Works** [comment]
Which commit are you on?

**Comment by vaimeo** [comment]
> Which commit are you on?

Latest dev commit

**Comment by Jack-Works** [comment]
I would suggest you try the following command:

First, stop all commands, then run:

```bash
pnpm prune
npx gulp clean
```

**Comment by vaimeo** [comment]
Thanks @Jack-Works that works.
