### ISSUE TITLE
[Crash] Error: <message not available>

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6146]
I was trying to add wallet in Tips, then Mask reports an error.

> <message not available>

Error stack:

<pre>Error
    at invariant (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-router.js:53:20)
    at useNavigate (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-router.js:542:40)
    at Steps (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/chunk.2153.js:842:58)
    at Nh (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-dom.js:172:137)
    at Lk (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-dom.js:295:386)
    at Kk (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-dom.js:285:379)
    at Jk (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-dom.js:285:310)
    at yk (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-dom.js:285:170)
    at Dk (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-dom.js:276:443)
    at uk (chrome-extension://bcipehiddbmkkcfbhlamkmfpiffnbihh/js/npm.react-dom.js:278:300)</pre>

## Build info
- Version: 2.7.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-04-24T09:29:23.300Z
- VERSION: v1.29.12-2293-gfb053bd69

## Git (*):

fb053bd69 (release/2.7.0) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
@guanbinrui looks like this is where you're using HashRouter. But don't add it back because it throws on Firefox.

**Comment by wenluomask** [comment]
Fixed
