### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6176]
I went into Twitter's profile page, maybe cause by NFT avatar, then Mask reports an error.

> Cannot read properties of undefined (reading 'filter')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'filter')
    at chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/chunk.3819.js:1556:103
    at Array.map (<anonymous>)
    at chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/chunk.3819.js:1556:46
    at Object.ri [as useMemo] (chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/npm.react-dom.js:183:119)
    at exports.useMemo (chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/6765.js:17133:208)
    at usePublicWallets (chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/chunk.3819.js:1553:47)
    at TipButton (chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/chunk.3819.js:1667:27)
    at Nh (chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/npm.react-dom.js:172:137)
    at cj (chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/npm.react-dom.js:220:217)
    at Lk (chrome-extension://fmnbefnmjobenpenbdlnnlfngpkbmbck/js/npm.react-dom.js:297:202)</pre>

## Build info
- Version: 2.7.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-04-27T10:50:24.729Z
- VERSION: v1.29.12-2326-gdfc4f3be9

## Git (*):

dfc4f3be9 (develop) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Fixed in https://github.com/DimensionDev/Maskbook/pull/6177
