### ISSUE TITLE
[Crash] Error: Minified React error #31

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#6258]
I was *doing something...*, then Mask reports an error.

> Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error stack:

<pre>Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bs%2C%20e%2C%20c%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at jh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:157:60)
    at w (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:161:186)
    at n (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:163:331)
    at C (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:167:334)
    at Xi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:215:300)
    at Lk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:299:57)
    at Kk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:379)
    at Jk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:310)
    at yk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:170)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:276:443)</pre>

## Build info
- Version: 2.7.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-04-27T09:19:06.484Z
- VERSION: v1.29.12-2314-g361375e7b

## Git ():

361375e7b (released) on tag "v2.7.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by septs** [comment]
```
Objects are not valid as a React child (found: object with keys {s, e, c}). If you meant to render a collection of children, use an array instead.
```

**Comment by Jack-Works** [comment]
what object has keys `s`, `e`, `c`? 🤔

**Comment by hanszhoou** [comment]
Fixed by https://github.com/DimensionDev/Maskbook/pull/6358
