### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'codePointAt')

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6269]
I went to current persona's contacts in dasboard, then Mask reports an error.
The pr I tried is https://github.com/DimensionDev/Maskbook/pull/6230

> Cannot read properties of undefined (reading 'codePointAt')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'codePointAt')
    at chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/chunk.2054.js:2224:110
    at Uh (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:172:137)
    at kj (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:221:270)
    at jj (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:219:204)
    at hj (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:218:176)
    at Uk (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:302:166)
    at Tk (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:285:389)
    at Sk (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:285:320)
    at Hk (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:285:180)
    at Mk (chrome-extension://jaacmnaeikdlfhdpnhcfojgepghlalnd/js/npm.react-dom.js:276:88)</pre>

**Comment by Jack-Works** [comment]
Problematic code:

https://github.com/DimensionDev/Maskbook/blob/003e77e0689f89a1c51837d3071e905ad4608a83/packages/dashboard/src/pages/Personas/components/ContactTableRow/index.tsx#L140

It is assuming every name includes second parts (`FirstName` `LastName`). Introduced in #6257 @septs

**Comment by septs** [comment]
@Jack-Works
