### ISSUE TITLE
[Crash] RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6282]
I tried ITO, then Mask reports an error.

> Incorrect locale information provided

Error stack:

<pre>RangeError: Incorrect locale information provided
    at String.localeCompare (<anonymous>)
    at chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/chunk.1588.js:3303:46
    at Array.sort (<anonymous>)
    at ExchangeTokenPanel (chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/chunk.1588.js:3303:31)
    at Uh (chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/npm.react-dom.js:172:137)
    at kj (chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/npm.react-dom.js:221:270)
    at Uk (chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/npm.react-dom.js:297:202)
    at Tk (chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/npm.react-dom.js:285:389)
    at Sk (chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/npm.react-dom.js:285:320)
    at Hk (chrome-extension://bbjgpccjnokcghikhpobimpplbndiich/js/npm.react-dom.js:285:180)</pre>

## Build info
- Version: 2.7.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-05-18T03:51:27.141Z
- VERSION: v1.29.12-2405-gc8f535d0b

## Git (*):

c8f535d0b (fix/seralizer) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/168962683-638ca1e1-940b-41c3-9ec7-84372894a7fb.png)

Made a quick check, the only sus call is in the solana library 🤔

**Comment by Jack-Works** [comment]
https://github.com/DimensionDev/Maskbook/pull/6286
