### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'dark')

### ISSUE THREAD

**Issue by bluescorpio** [DimensionDev/Maskbook#6289]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'dark')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'dark')
    at chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/chunk.441.js:124:54
    at chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/npm.tss-react.js:308:49
    at Object.useMemo (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/npm.react-dom.js:188:189)
    at exports.useMemo (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/7423.js:17133:208)
    at useStyles (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/npm.tss-react.js:297:51)
    at EthereumChainBoundary (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/chunk.441.js:156:56)
    at Uh (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/npm.react-dom.js:172:137)
    at Uk (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/npm.react-dom.js:295:386)
    at Tk (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/npm.react-dom.js:285:389)
    at Sk (chrome-extension://gjmehplehalbmaocjpfmpjclojdbfmem/js/npm.react-dom.js:285:320)</pre>

## Build info
- Version: 2.7.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-05-18T05:25:38.243Z
- VERSION: v1.29.12-2406-g7baf4aa84

## Git (*):

7baf4aa84 (fix/locales) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by bluescorpio** [comment]
在mask插件的钱包，点兑换。就报上面的错误

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/240fe4315c4216641608f0a093cbca674796c22d/packages/mask/src/web3/UI/EthereumChainBoundary.tsx#L37-L45
