### ISSUE TITLE
[Crash] Error: Failed to create token.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6359]
I changed from unsupported network(liked moonriver) to supported network(like Polygon) in MetaMask when I was in Swap page, then Mask reports an error.

> Failed to create token.

Error stack:

<pre>Error: Failed to create token.
    at createNativeToken (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/4925.js:40576:38)
    at chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/chunk.2670.js:3588:195
    at Oj (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/npm.react-dom.js:248:332)
    at Gk (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/npm.react-dom.js:291:111)
    at Dk (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/npm.react-dom.js:278:185)
    at ig (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/npm.react-dom.js:133:105)
    at Vk (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/npm.react-dom.js:288:419)
    at Ok (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/npm.react-dom.js:286:398)
    at Fk (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/npm.react-dom.js:275:269)
    at J (chrome-extension://hjilcllbmcipdjflaldemhagkdpagecj/js/4925.js:18158:203)</pre>

## Build info
- Version: 2.8.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-05-26T03:55:53.696Z
- VERSION: v1.29.12-2487-gb64753356

## Git (*):

b64753356 (lelenei/mf-411) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by supportactivator** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue https://direct.lc.chat/14234769
