### ISSUE TITLE
[Crash] Error: Invariant failed

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6423]
I was changing tokens to swap, then Mask reports an error.

> Invariant failed

Error stack:

<pre>Error: Invariant failed
    at invariant (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/6538.js:51406:15)
    at Price.quote (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/npm-ns.uniswap.sdk-core.js:458:129)
    at t.get (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/chunk.npm-ns.uniswap.v3-sdk.js:21:39451)
    at chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/chunk.6406.js:2044:32
    at Object.yi [as useMemo] (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/npm.react-dom.js:183:119)
    at exports.useMemo (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/6538.js:22619:208)
    at useTradeBreakdown (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/chunk.6406.js:2035:29)
    at useTradeComputed_useTradeComputed (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/chunk.6406.js:2061:23)
    at useAllTradeComputed (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/chunk.6406.js:3003:23)
    at useAllProviderTradeContext (chrome-extension://nhonfoihlfndbjdhnakimecideffichf/js/chunk.6406.js:3222:30)</pre>

## Build info
- Version: 2.8.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-06-02T10:21:46.340Z
- VERSION: v1.29.12-2494-gc554fb52d

## Git (*):

c554fb52d (hancheng/migrate-rp-ito-snapshot) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by nuanyang233** [comment]
close in #6424
