### ISSUE TITLE
[Crash] TypeError: Cannot contain / in a part of identifier

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#6450]
Browse on instagram
<img width="1434" alt="Screen Shot 2022-06-08 at 11 50 25" src="https://user-images.githubusercontent.com/6687437/172672699-256283ce-9a4a-4af9-b1d8-4becec56a111.png">

I was *doing something...*, then Mask reports an error.

> Cannot contain / in a part of identifier

Error stack:

<pre>TypeError: Cannot contain / in a part of identifier
    at banSlash (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6416.js:28686:36)
    at new PostIdentifier (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6416.js:28511:9)
    at Object.getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.9777.js:3435:24)
    at Object.getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1061.js:1029:31)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.9777.js:2068:38
    at Oj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:248:332)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:291:111)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:278:185)
    at ig (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:133:105)
    at Vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:288:419)</pre>

## Build info
- Version: 2.8.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-05-26T14:59:26.140Z
- VERSION: v1.29.12-2458-g7fb8cf4d9

## Git ():

7fb8cf4d9 (released) on tag "v2.8.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
Looks like the DOM selector selects the wrong user id that includes `/`. Or if Instagram really allows `/` in the user id, it should be converted into another character.
