### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'top')

### ISSUE THREAD

**Issue by bluescorpio** [DimensionDev/Maskbook#6453]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'top')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'top')
    at chrome-extension://okfnglacchodjngecppplckjonfndjac/js/chunk.168.js:2734:49
    at usePortalShadowRoot (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/4652.js:1859:12)
    at GuideStep (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/chunk.168.js:2723:90)
    at Uh (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/npm.react-dom.js:172:137)
    at kj (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/npm.react-dom.js:221:270)
    at Uk (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/npm.react-dom.js:297:202)
    at Tk (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/npm.react-dom.js:285:389)
    at Sk (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/npm.react-dom.js:285:320)
    at Hk (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/npm.react-dom.js:285:180)
    at Mk (chrome-extension://okfnglacchodjngecppplckjonfndjac/js/npm.react-dom.js:276:88)</pre>

## Build info
- Version: 2.8.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-06-08T15:55:28.911Z
- VERSION: v1.29.12-2524-g7db6ba3ef

## Git (*):

7db6ba3ef (develop) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by Jack-Works** [comment]
Hi can you give a reproduction?

**Comment by wenluomask** [comment]
It occurred when he went to step two of user guide.
It also refers to Jira: https://mask.atlassian.net/browse/MF-992

**Comment by Jack-Works** [comment]
closed by #6461
