### ISSUE TITLE
[Crash] TypeError: Cannot contain / in a part of identifier

### ISSUE THREAD

**Issue by toma1031** [DimensionDev/Maskbook#6500]
I was *doing something...*, then Mask reports an error.

> Cannot contain / in a part of identifier

Error stack:

<pre>TypeError: Cannot contain / in a part of identifier
    at banSlash (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6416.js:28686:36)
    at new PostIdentifier (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6416.js:28511:9)
    at Object.getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.9777.js:3435:24)
    at Object.getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1061.js:1029:31)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.9777.js:2068:38
    at Oj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:248:332)
    at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:291:111)
    at Vk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:288:358)
    at Ok (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:286:398)
    at Dk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:278:439)</pre>

## Build info
- Version: 2.8.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-05-26T14:59:26.140Z
- VERSION: v1.29.12-2458-g7fb8cf4d9

## Git ():

7fb8cf4d9 (released) on tag "v2.8.1"
git@github.com:DimensionDev/Maskbook.git

**Comment by supportactivator** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue https://direct.lc.chat/14234769

**Comment by Jack-Works** [comment]
Hello! Which SNS are you using?
