### ISSUE TITLE
[Crash] Error: Path parameter tokenId cannot be an empty string.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6552]
I was *doing something...*, then Mask reports an error.

> Path parameter tokenId cannot be an empty string.

Error stack:

<pre>Error: Path parameter tokenId cannot be an empty string.
    at chrome-extension://mgdeiighnooncgcioldoijlmdnifbbah/js/9074.js:53157:19
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at path (chrome-extension://mgdeiighnooncgcioldoijlmdnifbbah/js/9074.js:53144:33)
    at urlcatImpl (chrome-extension://mgdeiighnooncgcioldoijlmdnifbbah/js/9074.js:53097:14)
    at urlcat (chrome-extension://mgdeiighnooncgcioldoijlmdnifbbah/js/9074.js:53087:16)
    at Object.nonFungibleTokenLink (chrome-extension://mgdeiighnooncgcioldoijlmdnifbbah/js/9074.js:50010:65)
    at chrome-extension://mgdeiighnooncgcioldoijlmdnifbbah/js/chunk.6304.js:527:73
    at Array.map (<anonymous>)
    at NFTList (chrome-extension://mgdeiighnooncgcioldoijlmdnifbbah/js/chunk.6304.js:521:20)</pre>

## Build info
- Version: 2.9.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-06-14T13:31:13.766Z
- VERSION: v1.29.12-2619-g6a3b8842b

## Git (*):

6a3b8842b (release/2.9.0) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Fixed.
