### ISSUE TITLE
[Crash] TypeError: Please call setupPortalShadowRoot first

### ISSUE THREAD

**Issue by lelenei** [DimensionDev/Maskbook#6639]
I was *doing something...*, then Mask reports an error.

> Please call setupPortalShadowRoot first

Error stack:

<pre>TypeError: Please call setupPortalShadowRoot first
  at PortalShadowRoot (../theme/src/ShadowRoot/Portal.tsx:151:31)
  at eval (../theme/src/ShadowRoot/Portal.tsx:56:24)
  at useRefInit (../theme/src/ShadowRoot/Portal.tsx:158:37)
  at usePortalShadowRoot (../theme/src/ShadowRoot/Portal.tsx:54:40)
  at GuideStep (./src/components/GuideStep/index.tsx:193:80)
  at renderWithHooks (npm:react-dom/cjs/react-dom.development.js:16175:18)
  at mountIndeterminateComponent (npm:react-dom/cjs/react-dom.development.js:20908:13)
  at beginWork (npm:react-dom/cjs/react-dom.development.js:22411:16)
  at beginWork$1 (npm:react-dom/cjs/react-dom.development.js:27376:14)
  at performUnitOfWork (npm:react-dom/cjs/react-dom.development.js:26508:12)</pre>

## Build info
- Version: 2.9.0
- NODE_ENV: development
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-06-27T13:57:51.372Z
- VERSION: v1.29.12-2653-g7a9793266

## Git (*):

7a9793266 (lelenei/mf-786) on tag "v2.5.0"
https://github.com/DimensionDev/Maskbook.git

**Comment by NARULANEHA** [comment]
For a faster assistance click on the link below to speak to a customer service:-https://chatting.page/custormerservicedirect

**Comment by Jack-Works** [comment]
@lelenei how and where are you using it?
