### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'iconFilterColor')

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#6642]
I was trying to connect wallect connect, then Mask reports an error.

> Cannot read properties of undefined (reading 'iconFilterColor')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'iconFilterColor')
    at PluginWalletStatusBar (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/37.js:446:65)
    at Uh (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:172:137)
    at kj (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:221:270)
    at Uk (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:297:202)
    at Tk (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:285:389)
    at Sk (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:285:320)
    at Hk (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:285:180)
    at Mk (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:276:88)
    at Fk (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/npm.react-dom.js:273:429)
    at J (chrome-extension://aafllnlbljbfagebjhiaidkedganlmpb/js/4242.js:22811:203)</pre>

## Build info
- Version: 2.9.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-06-28T11:08:21.569Z
- VERSION: v1.29.12-2712-g120597648

## Git (*):

120597648 (lelenei/mf-411-new) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by wenluomask** [comment]
Refer to Jira: https://mask.atlassian.net/browse/MF-877
