### ISSUE TITLE
[Crash] Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by hh77hh88kt218** [DimensionDev/Maskbook#6669]
I was *doing something...*, then Mask reports an error.

> Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error stack:

<pre>Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at qh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:157:60)
    at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:167:372)
    at ej (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:216:419)
    at Uk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:299:117)
    at Tk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:389)
    at Sk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:320)
    at Hk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:285:180)
    at Mk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:276:88)
    at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:273:429)
    at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/9074.js:22903:203)</pre>

## Build info
- Version: 2.9.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-06-15T19:54:44.235Z
- VERSION: v1.29.12-2686-gcc4192a6f

## Git (*):

cc4192a6f (released) on tag "v2.5.0"
git@github.com:DimensionDev/Maskbook.git

**Comment by UncleBill** [comment]
@hh77hh88kt218 Thanks for reporting this.
It's very hard to identify bug from the information you have provided. Could you post a screenshot, or tell us how to reproduce the issue?
