### ISSUE TITLE
[Crash] UnknownError: The databases() promise was rejected.

### ISSUE THREAD

**Issue by trekeptor** [DimensionDev/Maskbook#6823]
I was *doing something...*, then Mask reports an error.

> The databases() promise was rejected.

Error stack:

<pre>DOMException: The databases() promise was rejected.
    at RecoverError (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1037:20)
    at onResponse (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1558:17)
    at handleSingleMessage (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1664:16)
    at rawMessageReceiver (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.async-call-rpc.js:1577:40)</pre>

**Comment by Jack-Works** [comment]
> databases() promise was rejected

This heard strange. hi, @ramanydv can you tell me how to reproduce that problem? that will be helpful.
