### ISSUE TITLE
[Crash] ReferenceError: Cannot access 'AllProviderTradeContext' before initialization

### ISSUE THREAD

**Issue by bluescorpio** [DimensionDev/Maskbook#6844]
I was *doing something...*, then Mask reports an error.

> Cannot access 'AllProviderTradeContext' before initialization

Error stack:

<pre>ReferenceError: Cannot access 'AllProviderTradeContext' before initialization
  at Object.TX (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/chunk.2778.js:573:30)
  at TraderDialog (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/chunk.9392.js:6123:192)
  at Uh (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:361:137)
  at Uk (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:484:386)
  at Tk (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:474:389)
  at Sk (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:474:320)
  at Hk (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:474:180)
  at Mk (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:465:88)
  at Dk (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:467:300)
  at ig (chrome-extension://bklpiioeppeglfkmbbalnoajicmbhjlc/js/npm.react-dom.js:322:105)</pre>

## Build info
- Version: 2.10.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-07-20T21:09:58.101Z
- VERSION: v1.29.12-2769-ga01774ec4

## Git (*):

a01774ec4 (feat/nft-card-ui)
git@github.com:DimensionDev/Maskbook.git

**Comment by nuanyang233** [comment]
Duplicate with #6821
