### ISSUE TITLE
[Crash] Error: Path parameter id cannot be an empty string.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#7094]
I went to activity tab of Looksrare in NFT plugin, then Mask reports an error.
You can check this tweet: https://twitter.com/nftwhalealert/status/1559728328839675904

https://user-images.githubusercontent.com/85149605/185039441-6dc4cd6f-cd85-4b03-83d8-eea5f00614bd.mov

> Path parameter id cannot be an empty string.

Error stack:

<pre>Error: Path parameter id cannot be an empty string.
  at chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/5043.js:36004:19
  at [Symbol.replace] (<anonymous>)
  at String.replace (<anonymous>)
  at path (chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/5043.js:35991:33)
  at urlcatImpl (chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/5043.js:35944:14)
  at urlcat (chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/5043.js:35934:16)
  at Object.transactionLink (chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/5958.js:3697:101)
  at NFTActivityCard (chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/chunk.23.js:3059:64)
  at Xh (chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/npm.react-dom.js:376:137)
  at Wk (chrome-extension://ilmhmmbbimfnnggfihpcelkpbgeccmmm/js/npm.react-dom.js:499:337)</pre>

## Build info
- Version: 2.12.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2022-08-16T09:44:34.187Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by Tedko** [comment]
Fixed?

**Comment by UncleBill** [comment]
> Fixed?

Should have been fixed.

https://github.com/DimensionDev/Maskbook/blob/ef5f9588091df5d3e8d7eb164054a7a60608f441/packages/mask/src/plugins/Collectible/src/SNSAdaptor/Shared/ActivityCard.tsx#L149-L157

The activity hash, which is the id in this error, will now be checked before being passed to the `Object.transactionLink`
