### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by lidiaa14** [DimensionDev/Maskbook#7106]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'toLowerCase')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.1719.js:999:40
    at baseUniq (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.lodash-es.js:4286:31)
    at uniqBy (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.lodash-es.js:12377:101)
    at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.1719.js:996:55
    at bi (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:363:46)
    at ci (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:364:451)
    at Object.useState (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:379:528)
    at exports.useState (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/4543.js:31:394)
    at NFTListDialog (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.1719.js:909:51)
    at Uh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:361:137)</pre>

## Build info
- Version: 2.10.3
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-08-07T13:03:50.861Z
- VERSION: v1.29.12-2879-g2cd93e36a

## Git (*):

2cd93e36a (released)
https://github.com/DimensionDev/Maskbook

**Comment by UncleBill** [comment]
Thanks for the report. It should have been fixed by 5621640e887b6fad19dbae7, will be released soon.
