### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading '0x934B510D4C9103E6a87AEf13b816fb080286D649')

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Maskbook#7529]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading '0x934B510D4C9103E6a87AEf13b816fb080286D649')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading '0x934B510D4C9103E6a87AEf13b816fb080286D649')
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/4627.js:1418:252
  at getCurrentValue (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5277.js:1416:20)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7657.js:1355:142
  at Object.qi [as useState] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:384:53)
  at exports.useState (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/2437.js:1158:394)
  at exports.useSubscription (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7657.js:1355:79)
  at useRecentTransactions (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/4909.js:994:91)
  at useToolbox (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.3374.js:3027:124)
  at ToolboxHintForWallet (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.3374.js:2970:102)
  at Xh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:376:137)</pre>

## Build info
- Version: 2.13.1
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-09-17T17:27:38.047Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by Tedko** [comment]
@wenluomask as mentioned in rock chat
