### ISSUE TITLE
[Crash] UnknownError: The databases() promise was rejected.

### ISSUE THREAD

**Issue by maragorat** [DimensionDev/Maskbook#8082]
I was *doing something...*, then Mask reports an error.

> The databases() promise was rejected.

Error stack:

<pre>DOMException: The databases() promise was rejected.
    at RecoverError (chrome-extension://hpokmeoiahdcikahdadbocdhobnkgokm/js/npm.async-call-rpc.js:1071:20)
    at onResponse (chrome-extension://hpokmeoiahdcikahdadbocdhobnkgokm/js/npm.async-call-rpc.js:1598:17)
    at handleSingleMessage (chrome-extension://hpokmeoiahdcikahdadbocdhobnkgokm/js/npm.async-call-rpc.js:1704:16)
    at rawMessageReceiver (chrome-extension://hpokmeoiahdcikahdadbocdhobnkgokm/js/npm.async-call-rpc.js:1617:40)</pre>

**Comment by Jack-Works** [comment]
How is this possible? 🤔 Hello @maragorat can you provide some information about your environment? For example, the Chrome version, incognito mode, etc
