### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'top')

### ISSUE THREAD

**Issue by guanbinrui** [DimensionDev/Maskbook#8156]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of undefined (reading 'top')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'top')
  at eval (./packages/mask/src/components/GuideStep/index.tsx:203:42)
  at usePortalShadowRoot (./packages/theme/src/ShadowRoot/Portal.tsx:83:12)
  at GuideStep (./packages/mask/src/components/GuideStep/index.tsx:202:80)
  at renderWithHooks (npm:react-dom/cjs/react-dom.development.js:18949:18)
  at updateFunctionComponent (npm:react-dom/cjs/react-dom.development.js:22867:20)
  at beginWork (npm:react-dom/cjs/react-dom.development.js:24980:16)
  at beginWork$1 (npm:react-dom/cjs/react-dom.development.js:32244:14)
  at performUnitOfWork (npm:react-dom/cjs/react-dom.development.js:31178:12)
  at workLoopSync (npm:react-dom/cjs/react-dom.development.js:31014:5)
  at renderRootSync (npm:react-dom/cjs/react-dom.development.js:30979:7)</pre>

## Build info
- Version: 2.16.0
- NODE_ENV: development
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2022-11-30T07:17:55.775Z
- VERSION: @masknet/encryption@0.1.2-110-g803be0eb9

## Git (*):

803be0eb9 (develop)
git@github.com:DimensionDev/Maskbook.git

**Comment by Lanttcat** [comment]
Fixed

**Comment by Lanttcat** [comment]
Fixed.
