### ISSUE TITLE
[Crash] TypeError: Cannot read properties of undefined (reading 'pluginID')

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#8490]
I search $eth and then check the NFT eth, then Mask reports an error.

> Cannot read properties of undefined (reading 'pluginID')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'pluginID')
  at TrendingView (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/chunk.9672.js:5768:129)
  at tj (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:479:151)
  at Jk (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:512:172)
  at fn (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:620:88)
  at cn (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:606:78)
  at bn (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:604:338)
  at Qm (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:604:158)
  at Sm (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:597:387)
  at Mm (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:599:306)
  at hh (chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:430:105)
  at chrome-extension://aokcfmjmmioijcijgbaleededdmokjjg/js/npm.react-dom.js:594:273</pre>

## Build info
- Version: 2.17.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2023-01-13T11:17:51.326Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by wenluomask** [comment]
Fixed in https://github.com/DimensionDev/Maskbook/pull/8489
