### ISSUE TITLE
[Crash] TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by harshvardhanrajdan** [DimensionDev/Maskbook#8549]
I was *doing something...*, then Mask reports an error.

> Cannot read properties of null (reading 'length')

Error stack:

<pre>TypeError: Cannot read properties of null (reading 'length')
  at name2Image (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7259.js:2469:29)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/7259.js:2494:36
  at tj (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:479:151)
  at Jk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:512:172)
  at Ik (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:509:203)
  at Gk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:508:176)
  at fn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:624:76)
  at cn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:606:78)
  at bn (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:604:338)
  at Qm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:604:158)
  at Sm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:597:387)
  at Om (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:595:274)
  at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6582.js:7159:206)
  at R (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/6582.js:7160:128)
  at queue.<computed> (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:3386:7)
  at run (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:3360:5)
  at MessagePort.listener (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:3371:3)</pre>

## Build info
- Version: 2.17.4
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2023-01-19T10:14:17.711Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by Tedko** [comment]
@wenluomask fyi

**Comment by guanbinrui** [comment]
CC @UncleBill
