### ISSUE TITLE
[Crash] ReferenceError: omitBy is not defined

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#8558]
Just open Welcome Page after installation, then Mask reports an error.

> omitBy is not defined

Error stack:

<pre>ReferenceError: omitBy is not defined
  at useChainContext (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/6325.js:13262:12)
  at TransactionSnackbar (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/chunk.8994.js:2123:109)
  at tj (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/npm.react-dom.js:479:151)
  at fn (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/npm.react-dom.js:618:335)
  at cn (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/npm.react-dom.js:606:78)
  at bn (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/npm.react-dom.js:604:338)
  at Qm (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/npm.react-dom.js:604:158)
  at Sm (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/npm.react-dom.js:597:387)
  at Om (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/npm.react-dom.js:595:274)
  at J (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/2633.js:6948:206)
  at R (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/js/2633.js:6949:128)
  at queue.<computed> (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/polyfill/ecmascript.js:3386:7)
  at run (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/polyfill/ecmascript.js:3360:5)
  at MessagePort.listener (chrome-extension://pdifapcjfjeaegbfcnklpnnhaogompcd/polyfill/ecmascript.js:3371:3)</pre>

**Comment by Jack-Works** [comment]
fixed by d8b752e291f506623844bf1c5bde400007e93353
