### ISSUE TITLE
[Crash] Error: Component must be wrapped with <Container.Provider>

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#8780]
I went to Web3 Profile's Activities tab, then Mask reports an error.

> Component must be wrapped with <Container.Provider>

Error stack:

<pre>Error: Component must be wrapped with <Container.Provider>
  at Object.useContainer (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/8645.js:57035:13)
  at FeedsPage (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/chunk.528.js:2730:92)
  at tj (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:479:151)
  at Jk (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:512:172)
  at Ik (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:509:203)
  at Gk (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:508:176)
  at fn (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:624:76)
  at cn (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:606:78)
  at bn (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:604:338)
  at Qm (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:604:158)
  at Sm (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:597:387)
  at Mm (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:599:306)
  at hh (chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:430:105)
  at chrome-extension://jinhgjpeephiojjfcifclppkpmpeebdk/js/npm.react-dom.js:594:273</pre>

## Build info
- Version: 2.17.7
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2023-02-23T02:54:23.635Z
- VERSION: undefined-reproducible

## Git ():

N/A (N/A)
N/A

**Comment by wenluomask** [comment]
Closed by https://github.com/DimensionDev/Maskbook/pull/8781
