### ISSUE TITLE
[Crash] TypeError: Cannot contain / in a part of identifier

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#8874]
I viewed tweet: https://twitter.com/LensProtocol/status/1631323252340719617 , then Mask reports an error under one of reply.
<img width="1117" alt="截屏2023-03-03 15 46 42" src="https://user-images.githubusercontent.com/85149605/222662047-700838fa-070c-4ee4-87bc-0bef71777040.png">

> Cannot contain / in a part of identifier: Cell Signaling Technology
@CellSignal
New to performing #immunohistochemistry experiments? Not getting the IHC results you want from your current experiments? Check out CST IHC resources for protocol videos, tech tips, and more! Better results are just a click away! http://cst-science.com/bdalyi?twclid=23enybf8nkat0bm8k4ql2drhgj
2
16.2K
Promoted

Error stack:

<pre>TypeError: Cannot contain / in a part of identifier: Cell Signaling Technology
@CellSignal
New to performing #immunohistochemistry experiments? Not getting the IHC results you want from your current experiments? Check out CST IHC resources for protocol videos, tech tips, and more! Better results are just a click away! http://cst-science.com/bdalyi?twclid=23enybf8nkat0bm8k4ql2drhgj
2
16.2K
Promoted
  at banSlash (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/8190.js:370:36)
  at new PostIdentifier (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/8190.js:212:69)
  at Object.getCurrentValue (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/chunk.6487.js:3325:24)
  at getCurrentValue (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/3057.js:1314:100)
  at Object.useSyncExternalStore (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:499:74)
  at exports.useSyncExternalStore (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/1297.js:1387:63)
  at exports.useSubscription (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/7573.js:1710:79)
  at Object.usePostInfoDetails (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/3057.js:936:112)
  at PostReplacer (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/chunk.6487.js:2176:69)
  at tj (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:479:151)
  at fn (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:618:335)
  at cn (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:606:78)
  at bn (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:604:338)
  at Qm (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:604:158)
  at Sm (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:597:387)
  at Om (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/npm.react-dom.js:595:274)
  at J (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/941.js:7061:206)
  at R (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/js/941.js:7062:128)
  at queue.<computed> (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/polyfill/ecmascript.js:3386:7)
  at run (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/polyfill/ecmascript.js:3360:5)
  at MessagePort.listener (chrome-extension://kcgnpfngheihdaiolepfohalhnnlpnpg/polyfill/ecmascript.js:3371:3)</pre>

## Build info
- Version: 2.18.0
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2023-03-03T07:34:17.126Z
- VERSION: 2.18.0*

## Git (*):

80157eb (release/2.18.0)

**Comment by wenluomask** [comment]
Refer to https://mask.atlassian.net/browse/MF-3568
