### ISSUE TITLE
[Crash] URIError: URI malformed

### ISSUE THREAD

**Issue by katohisanaga** [DimensionDev/Maskbook#9194]
I was *doing something...*, then Mask reports an error.

> URI malformed

Error stack:

<pre>URIError: URI malformed
  at decodeURIComponent (<anonymous>)
  at Object.getSearchedKeywordAtTwitter [as getSearchedKeyword] (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.2491.js:45:89)
  at onLocationChange (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.2147.js:2775:113)
  at chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.2147.js:2778:9
  at Al (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:557:137)
  at am (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:582:225)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:93)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:73)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:70)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)
  at em (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:585:421)
  at dm (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:584:69)</pre>

## Build info
- Version: 2.18.3
- NODE_ENV: production
- target: chromium
- build: stable
- architecture: web
- BUILD_DATE: 2023-03-28T14:39:44.483Z
- VERSION: 2.18.3*

## Git (*):

98dbced (HEAD)

**Comment by Tedko** [comment]
@wenluomask

**Comment by UncleBill** [comment]
@katohisanaga Thanks for reporting this. Can you tell more about what you searched for?
