### ISSUE TITLE
[Crash] TypeError: Cannot destructure property 'currentVisitingProfile' of '(0 , _dom_useSNSAdaptorContext_js__WEBPACK_IMPORTED_MODULE_1__.B)(...)' as it is undefined.

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#9953]
I just opened welcome page, then Mask reports an error.
Version: Develop 1358c90

> Cannot destructure property 'currentVisitingProfile' of '(0 , _dom_useSNSAdaptorContext_js__WEBPACK_IMPORTED_MODULE_1__.B)(...)' as it is undefined.

Error stack:

<pre>TypeError: Cannot destructure property 'currentVisitingProfile' of '(0 , _dom_useSNSAdaptorContext_js__WEBPACK_IMPORTED_MODULE_1__.B)(...)' as it is undefined.
  at useCurrentVisitingIdentity (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/1663.js:87:13)
  at useCurrentVisitingUser (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5634.js:63:81)
  at AnimatePic (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5634.js:841:21)
  at Jf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:425:143)
  at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:586:338)
  at Bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:572:321)
  at Ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:423)
  at ef (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:264)
  at ff (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:565:94)
  at pf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:563:263)
  at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5777.js:2195:206)
  at R (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5777.js:2196:128)
  at queue.<computed> (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2773:7)
  at run (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2747:5)
  at MessagePort.eventListener (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2758:3)</pre>

**Comment by wenluomask** [comment]
Refer to https://mask.atlassian.net/browse/MF-4393 .
