### ISSUE TITLE
[Crash] TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by wenluomask** [DimensionDev/Maskbook#9968]
I entered an incorrect verification code to continue when I tried to recover cloud backup, then Mask reports an error.

> Failed to construct 'URL': Invalid URL

Error stack:

<pre>TypeError: Failed to construct 'URL': Invalid URL
  at getFileName (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5855.js:396:17)
  at BackupInfoCard (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/chunk.5855.js:402:19)
  at Jf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:425:143)
  at rh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:469:172)
  at qh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:466:204)
  at oh (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:465:176)
  at Fk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:593:287)
  at Bk (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:572:321)
  at Ak (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:423)
  at ef (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:570:264)
  at ff (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:565:94)
  at pf (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/npm.react-dom.js:563:263)
  at J (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5777.js:2209:206)
  at R (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/js/5777.js:2210:128)
  at queue.<computed> (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2773:7)
  at run (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2747:5)
  at MessagePort.eventListener (chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/polyfill/ecmascript.js:2758:3)</pre>

**Comment by wenluomask** [comment]
Fixed by https://github.com/DimensionDev/Maskbook/pull/10050
